### ISSUE TITLE
[JENKINS-21664] Plugins with optional dependencies and compiled with Java6 cause Exception in loading

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#22854]
<p>Steps to produce the problem:</p>
<ol>
	<li>Install Copy Artifact</li>
	<li>Disable Maven plugin</li>
	<li>Restart Jenkins</li>
	<li>Fails to load Copy Artifact with: (full stacktrace is attached)

<pre>
1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/maven/MavenBuild
  at hudson.plugins.copyartifact.CopyArtifact$DescriptorImpl.<init>(Unknown Source)
</pre></li>
</ol>

<p>I found followings:</p>
<ul>
	<li>This can be reproduced when I package Copy Artifact with jdk 1.6.</li>
	<li>This cannot be reproduced when I package Copy Artifact with jdk 1.7.</li>
</ul>

<p>It seems that something strange happens in Jenkins plugin loading system.<br/>
It may be a problem with guice 4.0 introduced in <a href="https://github.com/jenkinsci/jenkins/commit/aea10298fed376979e41f4482dd6f2a916f4b23f" class="external-link" target="_blank" rel="nofollow noopener">aea10298</a> (may be guice does not work with Java1.6).</p>

<p>What I will do are:</p>
<ul>
	<li>Create a minimum plugin to reproduce the problem.</li>
	<li>Test what happens if reverted aea10298.</li>
	<li>Test what happens if downgrade guice to guice 3.0 (fails to compile?)</li>
</ul>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-21664" target="_blank">Plugins with optional dependencies and compiled with Java6 cause Exception in loading</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2014-02-10T14:08:54+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Steps to produce the problem:</p>
<ol>
	<li>Install Copy Artifact</li>
	<li>Disable Maven plugin</li>
	<li>Restart Jenkins</li>
	<li>Fails to load Copy Artifact with: (full stacktrace is attached)
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/maven/MavenBuild
  at hudson.plugins.copyartifact.CopyArtifact$DescriptorImpl.&lt;init&gt;(Unknown Source)
</pre>
</div></div></li>
</ol>

<p>I found followings:</p>
<ul>
	<li>This can be reproduced when I package Copy Artifact with jdk 1.6.</li>
	<li>This cannot be reproduced when I package Copy Artifact with jdk 1.7.</li>
</ul>

<p>It seems that something strange happens in Jenkins plugin loading system.
It may be a problem with guice 4.0 introduced in <a href="https://github.com/jenkinsci/jenkins/commit/aea10298fed376979e41f4482dd6f2a916f4b23f" class="external-link" target="_blank" rel="nofollow noopener">aea10298</a> (may be guice does not work with Java1.6).</p>

<p>What I will do are:</p>
<ul>
	<li>Create a minimum plugin to reproduce the problem.</li>
	<li>Test what happens if reverted aea10298.</li>
	<li>Test what happens if downgrade guice to guice 3.0 (fails to compile?)</li>
</ul>
</pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 1.532, 1.549<br/>
Copy Artifact 1.28
```
</details>
<details><summary><i>1 attachment</i></summary>

- [stacktrace.log](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/25249/stacktrace.log)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194516&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194516">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>when depending on maven-plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>&nbsp;</td>
</tr>
</tbody></table>
</div>


<p>when depending on an original plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6        </th>
<td class='confluenceTd'>reproduce </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>&nbsp;</td>
</tr>
</tbody></table>
</div>


<p>It seems nothing to do with guice...</p>
</pre>
</details>

</ul>
</details>

<p>when depending on maven-plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>when depending on an original plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'>reproduce </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>It seems nothing to do with guice...</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194586&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194586">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>This is not a issue with Jenkins, but Java language feature.
I wrote a tips note for this problem:
<a href="https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies</a></p>
</pre>
</details>

</ul>
</details>

<p>This is not a issue with Jenkins, but Java language feature.<br/>
I wrote a tips note for this problem:<br/>
<a href="https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies</a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-21274%22">JENKINS-21274</a>]</i>
