### ISSUE TITLE
[JENKINS-66527] intermittent NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#12157]
<p>About half of the times Jenkins fails to start.</p>

<p>The web UI displays:</p>

<pre>
java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer
  at jenkins.model.Jenkins.createComputer(Jenkins.java:3222)
  at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:162)
  at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:148)
  at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:48)
  at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:254)
  at hudson.model.Queue._withLock(Queue.java:1398)
  at hudson.model.Queue.withLock(Queue.java:1274)
  at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:240)
  at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1670)
  at jenkins.model.Jenkins.<init>(Jenkins.java:1023)
  at hudson.model.Hudson.<init>(Hudson.java:86)
  at hudson.model.Hudson.<init>(Hudson.java:82)
  at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
  at hudson.WebAppMain$3.run(WebAppMain.java:312)
</pre>

<p>The log contains dozens of exceptions and stacktraces.</p>

<p>Restarting often resolves the problem until the next time the service is restarted.</p>

<p>This occurred after upgrading from 2.263.3 to 2.303.1</p>

<p>The server was already running with OpenJDK11. That has not changed.</p>

<p> </p>

<p>Even a successful start results in 82345 lines of logging including 86 to 279 exceptions</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=bram_mertens">bram_mertens</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66527" target="_blank">intermittent NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>component(s)</b>: core
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-03-07T12:27:08+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>About half of the times Jenkins fails to start.</p>

<p>The web UI displays:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-none">java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer
  at jenkins.model.Jenkins.createComputer(Jenkins.java:3222)
  at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:162)
  at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:148)
  at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:48)
  at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:254)
  at hudson.model.Queue._withLock(Queue.java:1398)
  at hudson.model.Queue.withLock(Queue.java:1274)
  at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:240)
  at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1670)
  at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:1023)
  at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)
  at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)
  at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
  at hudson.WebAppMain$3.run(WebAppMain.java:312)
</pre>
</div></div>

<p>The log contains dozens of exceptions and stacktraces.</p>

<p>Restarting often resolves the problem until the next time the service is restarted.</p>

<p>This occurred after upgrading from 2.263.3 to 2.303.1</p>

<p>The server was already running with OpenJDK11. That has not changed.</p>

<p> </p>

<p>Even a successful start results in 82345 lines of logging including 86 to 279 exceptions</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>LTS 2.303.1</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>bram_mertens:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66527?focusedId=413100&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413100">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>It appears to be a problem with the update of openjdk.</p>

<p> </p>

<p>I reverted the entire update and tested by updating only openjdk:</p>

<p>---&gt; Package java-11-openjdk-headless.x86_64 1:11.0.6.10-1.el7_7 will be updated
---&gt; Package java-11-openjdk-headless.x86_64 1:11.0.12.0.7-0.el7_9 will be an update</p>

<p>After this jenkins crashes as described.</p>

<p>this is on RHEL7.</p>
</pre>
</details>

</ul>
</details>

<p>It appears to be a problem with the update of openjdk.</p>

<p> </p>

<p>I reverted the entire update and tested by updating only openjdk:</p>

<p>---> Package java-11-openjdk-headless.x86_64 1:11.0.6.10-1.el7_7 will be updated<br/>
---> Package java-11-openjdk-headless.x86_64 1:11.0.12.0.7-0.el7_9 will be an update</p>

<p>After this jenkins crashes as described.</p>

<p>this is on RHEL7.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66527?focusedId=413155&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413155">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We'll need more information about what makes your Jenkins installation different than the many installations where Jenkins 2.303.1 is running successfully with Java 11.</p>

<p>Darin Pope reported in the 2.303.1 live stream that he's running on CentOS 7.  The Jenkins Docker images use Adoptium Temurin Java 11.0.12, which should be very close to the rpm package you're using from RHEL 7.  Possibly a small amount of available memory?  Possibly some settings that are specific to your operating system?</p>
</pre>
</details>

</ul>
</details>

<p>We'll need more information about what makes your Jenkins installation different than the many installations where Jenkins 2.303.1 is running successfully with Java 11.</p>

<p>Darin Pope reported in the 2.303.1 live stream that he's running on CentOS 7.  The Jenkins Docker images use Adoptium Temurin Java 11.0.12, which should be very close to the rpm package you're using from RHEL 7.  Possibly a small amount of available memory?  Possibly some settings that are specific to your operating system?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>bram_mertens:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66527?focusedId=413215&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413215">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=markewaite" class="user-hover" rel="markewaite">markewaite</a>: Increasing the system's RAM from 2GB to 4GB does appear to resolve the problem.</p>

<p>This controller does run a lot (192) plugins but has hardly any jobs.
The <a href="https://www.jenkins.io/doc/book/installing/linux/]" title="https://www.jenkins.io/doc/book/installing/linux/" class="external-link" target="_blank" rel="nofollow noopener">[installation guide</a> still says 256MB of RAM is sufficient to run the base system.</p>

<p>Perhaps that needs to be reviewed?</p>

<p>The same page does recommend 4GB+ for a small team but this instance is hardly used. (It is used mainly to test upgrades, new plugins etc.).</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=markewaite" class="user-hover" rel="markewaite">markewaite</a>: Increasing the system's RAM from 2GB to 4GB does appear to resolve the problem.</p>

<p>This controller does run a lot (192) plugins but has hardly any jobs.<br/>
The <a href="https://www.jenkins.io/doc/book/installing/linux/]" title="https://www.jenkins.io/doc/book/installing/linux/" class="external-link" target="_blank" rel="nofollow noopener">[installation guide</a> still says 256MB of RAM is sufficient to run the base system.</p>

<p>Perhaps that needs to be reviewed?</p>

<p>The same page does recommend 4GB+ for a small team but this instance is hardly used. (It is used mainly to test upgrades, new plugins etc.).</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66527?focusedId=445873&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-445873">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>RHEL 7 is no longer supported by the Jenkins project.</p>
</pre>
</details>

</ul>
</details>

<p>RHEL 7 is no longer supported by the Jenkins project.</p>
