### ISSUE TITLE
[JENKINS-15686] Builds fail after upgrade to 1.488, work fine with 1.478

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#13072]
<p>An external job using this command </p>

<p>export JENKINS_HOME=<a href="http://127.0.0.1:8080" class="external-link" target="_blank" rel="nofollow noopener">http://127.0.0.1:8080</a></p>

<p>java <del>jar /opt/jenkins/jenkins-data/war/WEB-INF/lib/jenkins-core</del>*.jar testcron /u/sf/bbense/<br/>
bin/synctaylor 2>&1 > /dev/null</p>

<p>works fine in 1.478, but fails with this long error after upgrading to 1.488. <br/>
Reverting to 1.478 ( and changing file permissions to allow reading the jar file ) resolves the problem. </p>

<p><html><head><title>Error 500</title></head><br/>
<body bgcolor=#fff><h1>Status Code: 500</h1>Exception: java.lang.NoSuchMethodError:<br/>
hudson.model.RunMap.put(Lhudson/model/Run;)Lhudson/model/Run;<br>Stacktrace: <pre>javax.servlet.ServletException:<br/>
java.lang.NoSuchMethodError: hudson.model.RunMap.put(Lhudson/model/Run;)Lhudson/model/Run;<br/>
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:616)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:659)<br/>
at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:241)<br/>
at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br/>
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:574)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:659)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:488)<br/>
at org.kohsuke.stapler.Stapler.service(Stapler.java:162)<br/>
at javax.servlet.http.HttpServlet.service(HttpServlet.java:45)<br/>
at winstone.ServletConfiguration.execute(ServletConfiguration.java:248)<br/>
at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)<br/>
at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:376)<br/>
at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:95)<br/>
at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:87)<br/>
at winstone.FilterConfiguration.execute(FilterConfiguration.java:194)<br/>
at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:366)</p>

<p>All external jobs using this kind of script setup fail with 1.488. </p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/bbense.png" title="bbense's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=bbense">bbense</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-15686" target="_blank">Builds fail after upgrade to 1.488, work fine with 1.478</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2013-10-30T22:33:58+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>An external job using this command </p>

<p>export JENKINS_HOME=<a href="http://127.0.0.1:8080" class="external-link" target="_blank" rel="nofollow noopener">http://127.0.0.1:8080</a></p>

<p>java <del>jar /opt/jenkins/jenkins-data/war/WEB-INF/lib/jenkins-core</del>*.jar testcron /u/sf/bbense/
bin/synctaylor 2&gt;&amp;1 &gt; /dev/null</p>

<p>works fine in 1.478, but fails with this long error after upgrading to 1.488. 
Reverting to 1.478 ( and changing file permissions to allow reading the jar file ) resolves the problem. </p>

<p>&lt;html&gt;&lt;head&gt;&lt;title&gt;Error 500&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor=#fff&gt;&lt;h1&gt;Status Code: 500&lt;/h1&gt;Exception: java.lang.NoSuchMethodError:
hudson.model.RunMap.put(Lhudson/model/Run;)Lhudson/model/Run;&lt;br&gt;Stacktrace: &lt;pre&gt;javax.servlet.ServletException:
java.lang.NoSuchMethodError: hudson.model.RunMap.put(Lhudson/model/Run;)Lhudson/model/Run;
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:616)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:659)
        at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:241)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:574)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:659)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:488)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:162)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:45)
        at winstone.ServletConfiguration.execute(ServletConfiguration.java:248)
        at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)
        at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:376)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:95)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:87)
        at winstone.FilterConfiguration.execute(FilterConfiguration.java:194)
        at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:366)</p>

<p>All external jobs using this kind of script setup fail with 1.488. </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>RHEL 6, Jenkins running in stand-alone server mode on localhost</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-15487%22">JENKINS-15487</a>]</i>
