### ISSUE TITLE
[JENKINS-10058] "local class incompatible" error on build slave with IBM JRE after upgrading to 1.416

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#15909]
<p>After upgrading from Jenkins 1.413 to 1.416 the following error happens while executing a job on our z/Linux build slave:</p>

<pre>
ERROR: Failed to archive test reports
hudson.util.IOException2: remote file operation failed: /home<span class="code-comment">/*****/</span>jenkins/workspace/****** at hudson.remoting.Channel@​1bd7743:Runtime_zLinux_Slave
	at hudson.FilePath.act(FilePath.java:754)
	at hudson.FilePath.act(FilePath.java:740)
	at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:83)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:123)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:135)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:664)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:639)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:617)
	at hudson.model.Build$RunnerImpl.post2(Build.java:161)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:586)
	at hudson.model.Run.run(Run.java:1400)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:146)
Caused by: java.io.InvalidClassException: hudson.util.io.ParserConfigurator$1; local <span class="code-keyword">class </span>incompatible: stream classdesc serialVersionUID = 6472613931861772577, local <span class="code-keyword">class </span>serialVersionUID = -2178106894481500733
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:182)
	at hudson.remoting.UserRequest.perform(UserRequest.java:98)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
</pre>

<p>The JRE used on the build slave is "IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux s390x-64".</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fredg">fredg</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10058" target="_blank">"local class incompatible" error on build slave with IBM JRE after upgrading to 1.416</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2011-08-13T09:13:27+00:00
<li><b>votes</b>: 7
<li><b>watchers</b>: 8
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from Jenkins 1.413 to 1.416 the following error happens while executing a job on our z/Linux build slave:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">ERROR: Failed to archive test reports
hudson.util.IOException2: remote file operation failed: /home<span class="code-comment">/*****/</span>jenkins/workspace/****** at hudson.remoting.Channel@1bd7743:Runtime_zLinux_Slave
	at hudson.FilePath.act(FilePath.java:754)
	at hudson.FilePath.act(FilePath.java:740)
	at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:83)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:123)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:135)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:664)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:639)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:617)
	at hudson.model.Build$RunnerImpl.post2(Build.java:161)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:586)
	at hudson.model.Run.run(Run.java:1400)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:146)
Caused by: java.io.InvalidClassException: hudson.util.io.ParserConfigurator$1; local <span class="code-keyword">class </span>incompatible: stream classdesc serialVersionUID = 6472613931861772577, local <span class="code-keyword">class </span>serialVersionUID = -2178106894481500733
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:182)
	at hudson.remoting.UserRequest.perform(UserRequest.java:98)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
</pre>
</div></div>

<p>The JRE used on the build slave is "IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux s390x-64".</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 1.416<br/>
z/Linux (s390x) 64bit
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>fredg:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10058?focusedId=149676&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-149676">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/browse/JENKINS-10030" title="Builds fail in JUnit test archiving (since 1.416) if specifying JDK other than the container" class="issue-link" data-issue-key="JENKINS-10030"><del>JENKINS-10030</del></a> is probably related to this issue, as it shows the same InvalidClassException and also refers to IBM JDK</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/browse/JENKINS-10030" title="Builds fail in JUnit test archiving (since 1.416) if specifying JDK other than the container" class="issue-link" data-issue-key="JENKINS-10030"><del>JENKINS-10030</del></a> is probably related to this issue, as it shows the same InvalidClassException and also refers to IBM JDK</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>fredg:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10058?focusedId=149678&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-149678">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>After upgrading to Jenkins 1.417 the error disappeared, but another one popped up instead, see <a href="https://issues.jenkins.io/browse/JENKINS-10059" title="NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath after upgrading to 1.417" class="issue-link" data-issue-key="JENKINS-10059"><del>JENKINS-10059</del></a>.</p>

<p>I'd like to keep this bug report open as a reference until the underlying problem is solved.</p>
</pre>
</details>

</ul>
</details>

<p>After upgrading to Jenkins 1.417 the error disappeared, but another one popped up instead, see <a href="https://issues.jenkins.io/browse/JENKINS-10059" title="NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath after upgrading to 1.417" class="issue-link" data-issue-key="JENKINS-10059"><del>JENKINS-10059</del></a>.</p>

<p>I'd like to keep this bug report open as a reference until the underlying problem is solved.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/roman_mazur.jpg" title="roman_mazur's avatar" /> roman_mazur:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10058?focusedId=150218&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-150218">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Got this error after updating Jenkins to 1.419.</p>

<p>java version "1.6.0_22"
Java(TM) SE Runtime Environment (build 1.6.0_22-b04)
Java HotSpot(TM) Client VM (build 17.1-b03, mixed mode, sharing)</p>
</pre>
</details>

</ul>
</details>

<p>Got this error after updating Jenkins to 1.419.</p>

<p>java version "1.6.0_22"<br/>
Java(TM) SE Runtime Environment (build 1.6.0_22-b04)<br/>
Java HotSpot(TM) Client VM (build 17.1-b03, mixed mode, sharing)</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-10030%22">JENKINS-10030</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-10059%22">JENKINS-10059</a>]</i>
