### ISSUE TITLE
[JENKINS-62164] Error after update to 2.222.3 with pinned plugins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#11513]
<p>After upgrading to 2.222.3 (from 2.204.2) Jenkins fails to load properly and displays this error:</p>

<p><tt>java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer</tt><br/>
 {{ at jenkins.model.Jenkins.createComputer(Jenkins.java:3106)}}<br/>
 {{ at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:136)}}<br/>
 {{ at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:47)}}<br/>
 {{ at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:210)}}<br/>
 {{ at hudson.model.Queue._withLock(Queue.java:1399)}}<br/>
 {{ at hudson.model.Queue.withLock(Queue.java:1276)}}<br/>
 {{ at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:196)}}<br/>
 {{ at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1617)}}<br/>
 {{ at jenkins.model.Jenkins.<init>(Jenkins.java:998)}}<br/>
 {{ at hudson.model.Hudson.<init>(Hudson.java:85)}}<br/>
 {{ at hudson.model.Hudson.<init>(Hudson.java:81)}}<br/>
 {{ at hudson.WebAppMain$3.run(WebAppMain.java:233)}}<br/>
 <tt>Caused: hudson.util.HudsonFailedToLoad</tt><br/>
 {{ at hudson.WebAppMain$3.run(WebAppMain.java:247)}}</p>

<p> </p>

<p> </p>

<p><tt>$ java -version</tt><br/>
 <tt>java version "1.8.0_201"</tt><br/>
 <tt>Java(TM) SE Runtime Environment (build 1.8.0_201-b09)</tt><br/>
 <tt>Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)</tt></p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ickersep">ickersep</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164" target="_blank">Error after update to 2.222.3 with pinned plugins</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 1
<li><b>watchers</b>: 5
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading to 2.222.3 (from 2.204.2) Jenkins fails to load properly and displays this error:</p>

<p><tt>java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer</tt>
 {{ at jenkins.model.Jenkins.createComputer(Jenkins.java:3106)}}
 {{ at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:136)}}
 {{ at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:47)}}
 {{ at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:210)}}
 {{ at hudson.model.Queue._withLock(Queue.java:1399)}}
 {{ at hudson.model.Queue.withLock(Queue.java:1276)}}
 {{ at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:196)}}
 {{ at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1617)}}
 {{ at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:998)}}
 {{ at hudson.model.Hudson.&lt;init&gt;(Hudson.java:85)}}
 {{ at hudson.model.Hudson.&lt;init&gt;(Hudson.java:81)}}
 {{ at hudson.WebAppMain$3.run(WebAppMain.java:233)}}
 <tt>Caused: hudson.util.HudsonFailedToLoad</tt>
 {{ at hudson.WebAppMain$3.run(WebAppMain.java:247)}}</p>

<p> </p>

<p> </p>

<p><tt>$ java -version</tt>
 <tt>java version "1.8.0_201"</tt>
 <tt>Java(TM) SE Runtime Environment (build 1.8.0_201-b09)</tt>
 <tt>Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)</tt></p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Ubuntu 18.04</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ickersep:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=390169&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-390169">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I discovered that I have several pinned plugins (all with timestamps from 4-5 years ago). After I removed all the *.pinned files Jenkins starts again.</p>

<p> This is strange since <a href="https://wiki.jenkins.io/display/JENKINS/Pinned+Plugins" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins.io/display/JENKINS/Pinned+Plugins</a> mentions that the pinned plugins feature was removed in Jenkins 2, so I wouldn't have expected that this suddenly causes problems.</p>
</pre>
</details>

</ul>
</details>

<p>I discovered that I have several pinned plugins (all with timestamps from 4-5 years ago). After I removed all the *.pinned files Jenkins starts again.</p>

<p> This is strange since <a href="https://wiki.jenkins.io/display/JENKINS/Pinned+Plugins" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins.io/display/JENKINS/Pinned+Plugins</a> mentions that the pinned plugins feature was removed in Jenkins 2, so I wouldn't have expected that this suddenly causes problems.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=390195&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-390195">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The error doesn't look related to pinning.</p>

<p>My best guess is extraction of the war file failed, and trying again, perhaps with fewer files / more free disk space, worked.</p>
</pre>
</details>

</ul>
</details>

<p>The error doesn't look related to pinning.</p>

<p>My best guess is extraction of the war file failed, and trying again, perhaps with fewer files / more free disk space, worked.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=390196&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-390196">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>(Note that this feature was in fact removed, my previous response might give the wrong impression – internal APIs remain but behave as nothing is ever pinned.)</p>
</pre>
</details>

</ul>
</details>

<p>(Note that this feature was in fact removed, my previous response might give the wrong impression – internal APIs remain but behave as nothing is ever pinned.)</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>bizdelnick:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=408486&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-408486">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I got the same error after Jenkins restart.</p>

<p>java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer
	at jenkins.model.Jenkins.createComputer(Jenkins.java:3147)
	at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:146)
	at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:43)
	at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:220)
	at hudson.model.Queue._withLock(Queue.java:1384)
	at hudson.model.Queue.withLock(Queue.java:1261)
	at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:206)
	at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1634)
	at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:994)
	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:85)
	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:295)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:309)</p>

<p>Version 2.277.3.
The next restart attempt was successful. I guess there can be a race condition somewhere.</p>
</pre>
</details>

</ul>
</details>

<p>I got the same error after Jenkins restart.</p>

<p>java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson$MasterComputer<br/>
	at jenkins.model.Jenkins.createComputer(Jenkins.java:3147)<br/>
	at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:146)<br/>
	at hudson.model.AbstractCIBase.access$000(AbstractCIBase.java:43)<br/>
	at hudson.model.AbstractCIBase$2.run(AbstractCIBase.java:220)<br/>
	at hudson.model.Queue._withLock(Queue.java:1384)<br/>
	at hudson.model.Queue.withLock(Queue.java:1261)<br/>
	at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:206)<br/>
	at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1634)<br/>
	at jenkins.model.Jenkins.<init>(Jenkins.java:994)<br/>
	at hudson.model.Hudson.<init>(Hudson.java:85)<br/>
	at hudson.model.Hudson.<init>(Hudson.java:81)<br/>
	at hudson.WebAppMain$3.run(WebAppMain.java:295)<br/>
Caused: hudson.util.HudsonFailedToLoad<br/>
	at hudson.WebAppMain$3.run(WebAppMain.java:309)</p>

<p>Version 2.277.3.<br/>
The next restart attempt was successful. I guess there can be a race condition somewhere.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ascheman.png" title="ascheman's avatar" /> ascheman:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=412049&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-412049">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I had a similar problem today with a Docker based <tt>docker.io/jenkins/jenkins:2.289.1-lts-jdk11</tt> running on Fedora CoreOS with Podman. Even several restarts of podman and Jenkins (container) as well as reboots of the Linux machine didn't solve the problem. In between I was even confronted with a messed up iptables configuration.</p>

<p>In the end I deleted the unpacked (cached) <tt>war</tt> directory in <tt>/var/lib/jenkins</tt> and restarted the container to restore it (I should have only moved and compared the contents to investigate the problem further). Now everything seems to be working again.</p>
</pre>
</details>

</ul>
</details>

<p>I had a similar problem today with a Docker based <tt>docker.io/jenkins/jenkins:2.289.1-lts-jdk11</tt> running on Fedora CoreOS with Podman. Even several restarts of podman and Jenkins (container) as well as reboots of the Linux machine didn't solve the problem. In between I was even confronted with a messed up iptables configuration.</p>

<p>In the end I deleted the unpacked (cached) <tt>war</tt> directory in <tt>/var/lib/jenkins</tt> and restarted the container to restore it (I should have only moved and compared the contents to investigate the problem further). Now everything seems to be working again.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/douglasawh.png" title="douglasawh's avatar" /> douglasawh:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=413064&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413064">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We are also seeing this error in 2.263.4. I had previously postulated that this is a race condition, and I see others are thinking that as well. I am going to see if I can reopen this and see if we can provided the information necessary to get this figured out.</p>

<p>UPDATE: I Reopened it.</p>

<p><b>JDK Version</b>: openjdk version "11.0.12" 2021-07-20 LTS
Red Hat 8.4</p>
</pre>
</details>

</ul>
</details>

<p>We are also seeing this error in 2.263.4. I had previously postulated that this is a race condition, and I see others are thinking that as well. I am going to see if I can reopen this and see if we can provided the information necessary to get this figured out.</p>

<p>UPDATE: I Reopened it.</p>

<p><b>JDK Version</b>: openjdk version "11.0.12" 2021-07-20 LTS<br/>
Red Hat 8.4</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/douglasawh.png" title="douglasawh's avatar" /> douglasawh:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-62164?focusedId=413263&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413263">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The below is addressed to me, but there is no proprietary info, so I am just dumping it here as is. I would be curious to know if others are getting a rotating cast of errors.</p>

<p>------</p>

<p>I think we might have hit the jackpot in terms of trying to reproduce the issue that affected us back then. Here’s what happened:</p>
<ul>
	<li>Once the copy of the Prod Jenkins Home finished, <a href="https://support.cloudbees.com/hc/en-us/articles/203737684-How-can-I-prevent-jenkins-from-starting-new-jobs-after-a-restart-?page=92" class="external-link" target="_blank" rel="nofollow noopener">I started Jenkins into quiet mode</a> (I didn’t want a prod deployment that runs on a schedule running in stage by mistake). Jenkins started without issues</li>
	<li>Then, I disabled all the jobs (again to prevent a job from running by mistake whenever I took Jenkins out of quiet mode).</li>
	<li>Then, since we were running stage with production’s config, the stage controller actually connected to the prod AWS account to create the agents there. Ooops.</li>
	<li>Since having stage create its agents in the wrong AWS account is not ideal, I ran my configuration playbook in stage. Three restarts later and Jenkins didn’t crash in any of them. Stage configuration was successful!  <span class="image-wrap" style=""><img src="https://jira.roguewave.com/images/icons/emoticons/smile.png" height="16" width="16" style="border: 0px solid black" /></span></li>
	<li>From the UI, I disabled quiet mode, but I noticed the builds were not starting.</li>
</ul>


<p> </p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'><font color="#000000">2021-09-07 20:19:11.628+0000 <span class="error">&#91;id=29&#93;</span> SEVERE hudson.triggers.SafeTimerTask#run: Timer task hudson.model.Queue$MaintainTask@7a94f7bb failed</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000">java.lang.IllegalStateException: The class jenkins.security.QueueItemAuthenticatorConfiguration was not found, potentially not yet loaded</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.ExtensionList.getInstance(ExtensionList.java:166)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorConfiguration.get(QueueItemAuthenticatorConfiguration.java:61)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorConfiguration$ProviderImpl.getAuthenticators(QueueItemAuthenticatorConfiguration.java:70)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorProvider$IteratorImpl.hasNext(QueueItemAuthenticatorProvider.java:44)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue$Item.authenticate(Queue.java:2331)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Node.canTake(Node.java:401)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.makeFlyWeightTaskBuildable(Queue.java:1736)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.makeBuildable(Queue.java:1698)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.maintain(Queue.java:1546)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue$MaintainTask.doRun(Queue.java:2902)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.lang.Thread.run(Thread.java:829)</font></td>
</tr>
</tbody></table>
</div>


<p> </p>
<ul>
	<li>So I restarted Jenkins one more time (again, with the same configuration my playbook had left in the previous restart, no changes), when suddenly</li>
</ul>


<p> </p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'><font color="#000000">java.lang.IllegalStateException: Expected 1 instance of jenkins.security.s2m.AdminWhitelistRule but got 0</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.ExtensionList.lookupSingleton(ExtensionList.java:451)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.core.AdminWhitelistRuleConfigurator.instance(AdminWhitelistRuleConfigurator.java:59)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.core.AdminWhitelistRuleConfigurator.instance(AdminWhitelistRuleConfigurator.java:42)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:777)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:713)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:777)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:762)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:638)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:307)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:299)</font></td>
</tr>
</tbody></table>
</div>


<p> </p>
<ul>
	<li>This is an issue that has shown up before. Usually another restart fixes the issue, but I’ve now restarted Jenkins about 4 times and it still shows up that error. I’m hoping this will allow us to investigate a bit more what’s going on.</li>
</ul>

</pre>
</details>

</ul>
</details>

<p>The below is addressed to me, but there is no proprietary info, so I am just dumping it here as is. I would be curious to know if others are getting a rotating cast of errors.</p>

<p>------</p>

<p>I think we might have hit the jackpot in terms of trying to reproduce the issue that affected us back then. Here’s what happened:</p>
<ul>
	<li>Once the copy of the Prod Jenkins Home finished, <a href="https://support.cloudbees.com/hc/en-us/articles/203737684-How-can-I-prevent-jenkins-from-starting-new-jobs-after-a-restart-?page=92" class="external-link" target="_blank" rel="nofollow noopener">I started Jenkins into quiet mode</a> (I didn’t want a prod deployment that runs on a schedule running in stage by mistake). Jenkins started without issues</li>
	<li>Then, I disabled all the jobs (again to prevent a job from running by mistake whenever I took Jenkins out of quiet mode).</li>
	<li>Then, since we were running stage with production’s config, the stage controller actually connected to the prod AWS account to create the agents there. Ooops.</li>
	<li>Since having stage create its agents in the wrong AWS account is not ideal, I ran my configuration playbook in stage. Three restarts later and Jenkins didn’t crash in any of them. Stage configuration was successful!  <span class="image-wrap" style=""><img src="https://jira.roguewave.com/images/icons/emoticons/smile.png" height="16" width="16" style="border: 0px solid black" /></span></li>
	<li>From the UI, I disabled quiet mode, but I noticed the builds were not starting.</li>
</ul>


<p> </p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'><font color="#000000">2021-09-07 20:19:11.628+0000 <span class="error">&#91;id=29&#93;</span> SEVERE hudson.triggers.SafeTimerTask#run: Timer task hudson.model.Queue$MaintainTask@​7a94f7bb failed</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000">java.lang.IllegalStateException: The class jenkins.security.QueueItemAuthenticatorConfiguration was not found, potentially not yet loaded</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.ExtensionList.getInstance(ExtensionList.java:166)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorConfiguration.get(QueueItemAuthenticatorConfiguration.java:61)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorConfiguration$ProviderImpl.getAuthenticators(QueueItemAuthenticatorConfiguration.java:70)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.QueueItemAuthenticatorProvider$IteratorImpl.hasNext(QueueItemAuthenticatorProvider.java:44)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue$Item.authenticate(Queue.java:2331)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Node.canTake(Node.java:401)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.makeFlyWeightTaskBuildable(Queue.java:1736)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.makeBuildable(Queue.java:1698)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue.maintain(Queue.java:1546)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.model.Queue$MaintainTask.doRun(Queue.java:2902)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at java.base/java.lang.Thread.run(Thread.java:829)</font></td>
</tr>
</tbody></table>
</div>


<p> </p>
<ul>
	<li>So I restarted Jenkins one more time (again, with the same configuration my playbook had left in the previous restart, no changes), when suddenly</li>
</ul>


<p> </p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'><font color="#000000">java.lang.IllegalStateException: Expected 1 instance of jenkins.security.s2m.AdminWhitelistRule but got 0</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at hudson.ExtensionList.lookupSingleton(ExtensionList.java:451)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.core.AdminWhitelistRuleConfigurator.instance(AdminWhitelistRuleConfigurator.java:59)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.core.AdminWhitelistRuleConfigurator.instance(AdminWhitelistRuleConfigurator.java:42)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:777)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:713)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:777)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:762)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:638)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:307)</font></td>
</tr>
<tr>
<td class='confluenceTd'><font color="#000000"> at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:299)</font></td>
</tr>
</tbody></table>
</div>


<p> </p>
<ul>
	<li>This is an issue that has shown up before. Usually another restart fixes the issue, but I’ve now restarted Jenkins about 4 times and it still shows up that error. I’m hoping this will allow us to investigate a bit more what’s going on.</li>
</ul>
