### ISSUE TITLE
[JENKINS-35129] After upgrade of 1.650 to 2.6 - unable to configure jobs

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#17178]
<p><a href="http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure" class="external-link" target="_blank" rel="nofollow noopener">http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure</a></p>

<pre>
May 25, 2016 10:05:38 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: d.helpFile in /view/Misc/job/Node-Keep-Alive/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)

Caused by: java.lang.NoClassDefFoundError: hudson/tasks/Ant
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods0(Native Method)
at java.lang.<span class="code-object">Class</span>.privateGetDeclaredMethods(<span class="code-object">Class</span>.java:2625)
at java.lang.<span class="code-object">Class</span>.getDeclaredMethods(<span class="code-object">Class</span>.java:1868)
at org.kohsuke.stapler.ClassDescriptor.findMethods(ClassDescriptor.java:148)
at org.kohsuke.stapler.ClassDescriptor.<init>(ClassDescriptor.java:84)
at org.kohsuke.stapler.MetaClass.buildDispatchers(MetaClass.java:106)
at org.kohsuke.stapler.MetaClass.<init>(MetaClass.java:94)
at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:203)
at org.kohsuke.stapler.jelly.groovy.GroovyFacet.createRequestDispatcher(GroovyFacet.java:106)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:257)
at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:252)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:742)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:724)
at hudson.model.Descriptor.getHelpFile(Descriptor.java:713)
... 167 more
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Ant
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
... 181 more
</pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/alex_carr.png" title="alex_carr's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alex_carr">alex_carr</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129" target="_blank">After upgrade of 1.650 to 2.6 - unable to configure jobs</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2016-06-01T16:12:54+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p><a href="http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure" class="external-link" target="_blank" rel="nofollow noopener">http://10.101.6.243:8080/view/Misc/job/Node-Keep-Alive/configure</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">May 25, 2016 10:05:38 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: d.helpFile in /view/Misc/job/Node-Keep-Alive/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
        at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)

Caused by: java.lang.NoClassDefFoundError: hudson/tasks/Ant
        at java.lang.<span class="code-object">Class</span>.getDeclaredMethods0(Native Method)
        at java.lang.<span class="code-object">Class</span>.privateGetDeclaredMethods(<span class="code-object">Class</span>.java:2625)
        at java.lang.<span class="code-object">Class</span>.getDeclaredMethods(<span class="code-object">Class</span>.java:1868)
        at org.kohsuke.stapler.ClassDescriptor.findMethods(ClassDescriptor.java:148)
        at org.kohsuke.stapler.ClassDescriptor.&lt;init&gt;(ClassDescriptor.java:84)
        at org.kohsuke.stapler.MetaClass.buildDispatchers(MetaClass.java:106)
        at org.kohsuke.stapler.MetaClass.&lt;init&gt;(MetaClass.java:94)
        at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:203)
        at org.kohsuke.stapler.jelly.groovy.GroovyFacet.createRequestDispatcher(GroovyFacet.java:106)
        at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:257)
        at org.kohsuke.stapler.RequestImpl.getView(RequestImpl.java:252)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:742)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:724)
        at hudson.model.Descriptor.getHelpFile(Descriptor.java:713)
        ... 167 more
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Ant
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
        at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
        ... 181 more
</pre>
</div></div></pre>
</details>
</details>
<details><summary><i>1 attachment</i></summary>

- [catalina.out](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/32803/catalina.out)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/alex_carr.png" title="alex_carr's avatar" /> alex_carr:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129?focusedId=258865&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-258865">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Work around: A downgrade of the Ant Plugin from 1.3 to 1.2 followed by an upgrade back to 1.3 and the exception above no longer occurs.</p>

<p>Note: At this point I seem to be experiencing the issue reported in: <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> - Job configuration screen stuck on LOADING</p>
</pre>
</details>

</ul>
</details>

<p>Work around: A downgrade of the Ant Plugin from 1.3 to 1.2 followed by an upgrade back to 1.3 and the exception above no longer occurs.</p>

<p>Note: At this point I seem to be experiencing the issue reported in: <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> - Job configuration screen stuck on LOADING</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129?focusedId=259230&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259230">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>It's not related to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a>. Could you please check if you have the Ant plugin installed? Maybe it has not been activated on 2.6 due to the whatever reason</p>
</pre>
</details>

</ul>
</details>

<p>It's not related to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a>. Could you please check if you have the Ant plugin installed? Maybe it has not been activated on 2.6 due to the whatever reason</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/alex_carr.png" title="alex_carr's avatar" /> alex_carr:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129?focusedId=259242&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259242">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yes, the Ant plugin is installed and activated. The downgrade and then upgrade of the Ant plugin resolved that problem (e.g. I no longer get an exception).</p>

<p>The only reason I linked this issue to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> is that it describes the problem that I am now dealing with.</p>
</pre>
</details>

</ul>
</details>

<p>Yes, the Ant plugin is installed and activated. The downgrade and then upgrade of the Ant plugin resolved that problem (e.g. I no longer get an exception).</p>

<p>The only reason I linked this issue to <a href="https://issues.jenkins.io/browse/JENKINS-35122" title="Job configuration screen stuck on LOADING" class="issue-link" data-issue-key="JENKINS-35122"><del>JENKINS-35122</del></a> is that it describes the problem that I am now dealing with.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129?focusedId=259600&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259600">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Weird. Corrupted zip file/full disk resulting in failed plugin install, something like that?</p>

<p>Difficult to determine after the fact.</p>
</pre>
</details>

</ul>
</details>

<p>Weird. Corrupted zip file/full disk resulting in failed plugin install, something like that?</p>

<p>Difficult to determine after the fact.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/alex_carr.png" title="alex_carr's avatar" /> alex_carr:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-35129?focusedId=259607&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-259607">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Plenty of disk space. Possibly a corrupted download. All set, thanks.</p>
</pre>
</details>

</ul>
</details>

<p>Plenty of disk space. Possibly a corrupted download. All set, thanks.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-35122%22">JENKINS-35122</a>]</i>
