### ISSUE TITLE
[JENKINS-787] a number of classes not found in v 1.135

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#13823]
<p>after upgrading from 1.132  to 1.135 most of hudson instances are not able to<br/>
start due to missing classes. </p>

<p>java.lang.NoClassDefFoundError: com/thoughtworks/xstream/core/JVM<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:50)</p>

<p>.....</p>

<p>java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildException<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:127)<br/>
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)<br/>
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)<br/>
	at winstone.HostConfiguration.(HostConfiguration.java:73)<br/>
....<br/>
java.lang.NoClassDefFoundError: org/jfree/chart/axis/CategoryAxis<br/>
	at hudson.model.Items.(Items.java:27)<br/>
	at hudson.model.Hudson.(Hudson.java:236)<br/>
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:105)<br/>
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)<br/>
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)<br/>
	at winstone.HostConfiguration.(HostConfiguration.java:73)<br/>
	at winstone.HostGroup.initHost(HostGroup.java:85)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=eirikma">eirikma</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-787" target="_blank">a number of classes not found in v 1.135</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: core
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2007-09-04T11:04:53+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 0
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>after upgrading from 1.132  to 1.135 most of hudson instances are not able to
start due to missing classes. </p>

<p>java.lang.NoClassDefFoundError: com/thoughtworks/xstream/core/JVM
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:50)</p>

<p>.....</p>

<p>java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildException
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:127)
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)
	at winstone.HostConfiguration.(HostConfiguration.java:73)
....
java.lang.NoClassDefFoundError: org/jfree/chart/axis/CategoryAxis
	at hudson.model.Items.(Items.java:27)
	at hudson.model.Hudson.(Hudson.java:236)
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:105)
	at winstone.WebAppConfiguration.(WebAppConfiguration.java:889)
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)
	at winstone.HostConfiguration.(HostConfiguration.java:73)
	at winstone.HostGroup.initHost(HostGroup.java:85)</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Platform: All, OS: All</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/kohsuke.png" title="kohsuke's avatar" /> kohsuke:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-787?focusedId=121984&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-121984">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The war file size is about the same as 1.134, and given the fully automated
release process and the changes in 1.135 I find it unlikely thatthe war contents
is corrupted.</p>

<p>Can you wipe off the Winstone temporary directory (/tmp/winstone) and retry?</p>
</pre>
</details>

</ul>
</details>

<p>The war file size is about the same as 1.134, and given the fully automated<br/>
release process and the changes in 1.135 I find it unlikely thatthe war contents<br/>
is corrupted.</p>

<p>Can you wipe off the Winstone temporary directory (/tmp/winstone) and retry?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>eirikma:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-787?focusedId=121985&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-121985">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm trying this version at home now. Seems to be working. I haven't got the same
set of mixed project-type configuration as some of the instances have at work,
though. </p>

<p>The problems <em>can</em> have been caused by our web proxy, but I haven't confirmed
that yet. Some of the microsoft ISA servers (as crucial to the nation's security
and the inhabitants' welfare as the berlin wall was to east germany...) are
configured to rewrite zip/jar files with java classes, injecting custom
classloaders and main classes, to prevent malicious code from entering the
building. In 90% of the cases this totally blows up the application, of course. </p>

<p>The classes are at least present in the version I downloaded home, and it seems
to be able to build tapestry5 (maven2 module with sub-modules).</p>

<p>Since one of the hudson servers started and I have no problems at home, I'll set
the issue to INVALID until it is confirmed that the issue exists more than one
place. It seems like the one to blame this time is the security system that
prevents our work from getting interrupted by malfunctional software. What would
we do without it.</p>
</pre>
</details>

</ul>
</details>

<p>I'm trying this version at home now. Seems to be working. I haven't got the same<br/>
set of mixed project-type configuration as some of the instances have at work,<br/>
though. </p>

<p>The problems <em>can</em> have been caused by our web proxy, but I haven't confirmed<br/>
that yet. Some of the microsoft ISA servers (as crucial to the nation's security<br/>
and the inhabitants' welfare as the berlin wall was to east germany...) are<br/>
configured to rewrite zip/jar files with java classes, injecting custom<br/>
classloaders and main classes, to prevent malicious code from entering the<br/>
building. In 90% of the cases this totally blows up the application, of course. </p>

<p>The classes are at least present in the version I downloaded home, and it seems<br/>
to be able to build tapestry5 (maven2 module with sub-modules).</p>

<p>Since one of the hudson servers started and I have no problems at home, I'll set<br/>
the issue to INVALID until it is confirmed that the issue exists more than one<br/>
place. It seems like the one to blame this time is the security system that<br/>
prevents our work from getting interrupted by malfunctional software. What would<br/>
we do without it.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>eirikma:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-787?focusedId=121986&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-121986">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>No sign of ISA-server thrashing in the war file. Still, a new download solved
the problem. Have no idea why, but the case should remain closed RESOLVED INVALID.</p>
</pre>
</details>

</ul>
</details>

<p>No sign of ISA-server thrashing in the war file. Still, a new download solved<br/>
the problem. Have no idea why, but the case should remain closed RESOLVED INVALID.</p>
