### ISSUE TITLE
[JENKINS-66198] Computer loadstatistics is broken since 2.289.1.2 - api shows data, but graphs do not render.

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#12119]
<p>Beginning with upgrade to 2.289.1.2 we noticed that loadStatistics for labels and agents is now borked.</p>

<p>E.g. /label/VALIDLABEL/load-statistics shows a broken icon for the statistics, while <br/>
/label/VALIDLABEL/loadStatistics/graph?type=min&width=1295&height=500</p>

<p>Shows an OOPS demon jenkins with an error. </p>

<p>However `label/VALIDLABEL/api/python?pretty=true&depth=3` does provide the expected values.</p>

<p>See attached screenshots.</p>

<p>We also recently removed several plugins as suggested by the Jenkins Health Advisor (tables-to-div issues as well as obsolete plugins).</p>

<p>We make use of these statistics to help understand loads on our agents - usually by LABEL.<br/>
Load-statistics are similarly broken for agents, too, e.g.</p>

<p>`/computer/VALIDAGENTNAME/load-statistics` is similarly broken.</p>

<p>Since we had recently upgraded the monitoring plugin, we downgraded that and restarted but no help there.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/stevenc.jpg" title="stevenc's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=stevenc">stevenc</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66198" target="_blank">Computer loadstatistics is broken since 2.289.1.2 - api shows data, but graphs do not render.</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>label(s)</b>: exception, regression, slave
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2021-08-02T13:24:26+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Beginning with upgrade to 2.289.1.2 we noticed that loadStatistics for labels and agents is now borked.</p>

<p>E.g. /label/VALIDLABEL/load-statistics shows a broken icon for the statistics, while 
/label/VALIDLABEL/loadStatistics/graph?type=min&amp;width=1295&amp;height=500</p>

<p>Shows an OOPS demon jenkins with an error. </p>

<p>However `label/VALIDLABEL/api/python?pretty=true&amp;depth=3` does provide the expected values.</p>

<p>See attached screenshots.</p>

<p>We also recently removed several plugins as suggested by the Jenkins Health Advisor (tables-to-div issues as well as obsolete plugins).</p>

<p>We make use of these statistics to help understand loads on our agents - usually by LABEL.
Load-statistics are similarly broken for agents, too, e.g.</p>

<p>`/computer/VALIDAGENTNAME/load-statistics` is similarly broken.</p>

<p>Since we had recently upgraded the monitoring plugin, we downgraded that and restarted but no help there.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
core 2.289.1.2; monitoring:1.87.0 and monitoring:1.88.0; metrics:4.0.2.7 <br/>
and other assorted plugins.
```
</details>
<details><summary><i>4 attachments</i></summary>

- [cloudbees-loadstats-data.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55241/cloudbees-loadstats-data.png)
  > ![cloudbees-loadstats-data.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55241/cloudbees-loadstats-data.png)
- [cloudbees-loadstats-graph.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55242/cloudbees-loadstats-graph.png)
  > ![cloudbees-loadstats-graph.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55242/cloudbees-loadstats-graph.png)
- [cloudbees-loadstats-page.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55243/cloudbees-loadstats-page.png)
  > ![cloudbees-loadstats-page.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55243/cloudbees-loadstats-page.png)
- [screenshot-1.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55317/screenshot-1.png)
  > ![screenshot-1.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55317/screenshot-1.png)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/stevenc.jpg" title="stevenc's avatar" /> stevenc:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66198?focusedId=411580&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-411580">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>It's probably worth noting that the "Load Statistics" selection for labels or agents maps to "load-statistics" in the URL but the api is loadStatistics. This doesn't seem to be different from before, but the inconsistent mappings are "interesting".</p>
</pre>
</details>

</ul>
</details>

<p>It's probably worth noting that the "Load Statistics" selection for labels or agents maps to "load-statistics" in the URL but the api is loadStatistics. This doesn't seem to be different from before, but the inconsistent mappings are "interesting".</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66198?focusedId=411582&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-411582">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Thanks for the report.  I was worried that the fix for <a href="https://issues.jenkins.io/browse/JENKINS-65336" title="Load statistics timespan does not affect image" class="issue-link" data-issue-key="JENKINS-65336"><del>JENKINS-65336</del></a> that was included in <a href="https://github.com/jenkinsci/jenkins/pull/5408" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/5408</a> as part of Jenkins 2.289.1 might be a cause of the problem, but I don't see the problem with Jenkins 2.289.2 and I didn't see the problem with 2.289.1.</p>
</pre>
</details>

</ul>
</details>

<p>Thanks for the report.  I was worried that the fix for <a href="https://issues.jenkins.io/browse/JENKINS-65336" title="Load statistics timespan does not affect image" class="issue-link" data-issue-key="JENKINS-65336"><del>JENKINS-65336</del></a> that was included in <a href="https://github.com/jenkinsci/jenkins/pull/5408" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/5408</a> as part of Jenkins 2.289.1 might be a cause of the problem, but I don't see the problem with Jenkins 2.289.2 and I didn't see the problem with 2.289.1.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/stevenc.jpg" title="stevenc's avatar" /> stevenc:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66198?focusedId=411585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-411585">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Digging into the logs, this stands out:
java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart</p>

<p>However I'm just floundering around in Kibana looking at logs from a dozen different jenkins servers... But this was close in time to the exception thrown. </p>

<p>And of course, I'm producing this problem in a Cloudbees Jenkins Enterprise solution, not the OSS solution... so perhaps it's something specific to Cloudbees.</p>
</pre>
</details>

</ul>
</details>

<p>Digging into the logs, this stands out:<br/>
java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart</p>

<p>However I'm just floundering around in Kibana looking at logs from a dozen different jenkins servers... But this was close in time to the exception thrown. </p>

<p>And of course, I'm producing this problem in a Cloudbees Jenkins Enterprise solution, not the OSS solution... so perhaps it's something specific to Cloudbees.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/timja.png" title="timja's avatar" /> timja:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-66198?focusedId=411943&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-411943">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>It works fine on 2.289.3, </p>

<p> <span class="image-wrap" style=""><a id="55317_thumb" href="https://issues.jenkins.io/secure/attachment/55317/55317_screenshot-1.png" title="screenshot-1.png" file-preview-type="image" file-preview-id="55317" file-preview-title="screenshot-1.png"><img src="https://issues.jenkins.io/secure/thumbnail/55317/_thumb_55317.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p><a href="https://ci.jenkins.io/computer/EC2%20(aws)%20-%20Ubuntu%2020.04%20LTS%20(i-0229f48a4a7af3183)/load-statistics" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/computer/EC2%20(aws)%20-%20Ubuntu%2020.04%20LTS%20(i-0229f48a4a7af3183)/load-statistics</a></p>

<p>Please re-produce with Jenkins itself and not the cloudbees offering</p>
</pre>
</details>

</ul>
</details>

<p>It works fine on 2.289.3, </p>

<p> <span class="image-wrap" style=""><a id="55317_thumb" href="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55317/screenshot-1.png" title="screenshot-1.png" file-preview-type="image" file-preview-id="55317" file-preview-title="screenshot-1.png"><img src="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/55317/screenshot-1.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p><a href="https://ci.jenkins.io/computer/EC2%20(aws)%20-%20Ubuntu%2020.04%20LTS%20(i-0229f48a4a7af3183)/load-statistics" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/computer/EC2%20(aws)%20-%20Ubuntu%2020.04%20LTS%20(i-0229f48a4a7af3183)/load-statistics</a></p>

<p>Please re-produce with Jenkins itself and not the cloudbees offering</p>
