### ISSUE TITLE
[JENKINS-7380] Latest version 1.375 crashes in Glassfish ver. 3.0.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#19800]
<p>After deployment, when navigating to the applications web page <a href="http://localhost:8080/hudson" class="external-link" target="_blank" rel="nofollow noopener">http://localhost:8080/hudson</a>, it crashes with the following error:</p>

<p>HTTP Status 500 - </p>

<p>--------------------------------------------------------------------------------</p>

<p>type Exception report</p>

<p>message</p>

<p>descriptionThe server encountered an internal error () that prevented it from fulfilling this request.</p>

<p>exception </p>

<p>javax.servlet.ServletException: PWC1243: Filter execution threw an exception<br/>
root cause </p>

<p>java.lang.NoClassDefFoundError: hudson/ivy/IvyModuleSetBuild<br/>
root cause </p>

<p>java.lang.ClassNotFoundException: hudson.ivy.IvyModuleSetBuild<br/>
note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 3.0.1 logs.</p>

<p>--------------------------------------------------------------------------------</p>

<p>GlassFish Server Open Source Edition 3.0.1</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alnikolov">alnikolov</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380" target="_blank">Latest version 1.375 crashes in Glassfish ver. 3.0.1</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: core
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2011-04-22T21:38:48+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After deployment, when navigating to the applications web page <a href="http://localhost:8080/hudson" class="external-link" target="_blank" rel="nofollow noopener">http://localhost:8080/hudson</a>, it crashes with the following error:</p>

<p>HTTP Status 500 - </p>

<p>--------------------------------------------------------------------------------</p>

<p>type Exception report</p>

<p>message</p>

<p>descriptionThe server encountered an internal error () that prevented it from fulfilling this request.</p>

<p>exception </p>

<p>javax.servlet.ServletException: PWC1243: Filter execution threw an exception
root cause </p>

<p>java.lang.NoClassDefFoundError: hudson/ivy/IvyModuleSetBuild
root cause </p>

<p>java.lang.ClassNotFoundException: hudson.ivy.IvyModuleSetBuild
note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 3.0.1 logs.</p>

<p>--------------------------------------------------------------------------------</p>

<p>GlassFish Server Open Source Edition 3.0.1</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Slakware Linux, GlassFish Server Open Source Edition 3.0.1 (build 22)</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/kboz.jpg" title="kboz's avatar" /> kboz:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141526&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141526">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>This problem is not dependent on using GlassFish.
It is probably related to one or more other installed plugins, rather than Hudson itself. The copyartifact plugin, for example, specifically causes this problem.
Workaround: Rollback to 1.374, install the Ivy plugin, then reload 1.375</p>
</pre>
</details>

</ul>
</details>

<p>This problem is not dependent on using GlassFish.<br/>
It is probably related to one or more other installed plugins, rather than Hudson itself. The copyartifact plugin, for example, specifically causes this problem.<br/>
Workaround: Rollback to 1.374, install the Ivy plugin, then reload 1.375</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/abayer.png" title="abayer's avatar" /> abayer:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141527&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141527">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yeah, I can verify that I'm not seeing this on a completely fresh install run via "java -jar hudson.war" with 1.375. I'm guessing you have one or more jobs configured as Ivy builds but don't have the Ivy plugin installed.</p>
</pre>
</details>

</ul>
</details>

<p>Yeah, I can verify that I'm not seeing this on a completely fresh install run via "java -jar hudson.war" with 1.375. I'm guessing you have one or more jobs configured as Ivy builds but don't have the Ivy plugin installed.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/kboz.jpg" title="kboz's avatar" /> kboz:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141528&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141528">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>It actually happens even if you have no Ivy builds configured.
For some reason the Copy Artifact Plugin v1.8, for example, suddenly also requires the Ivy plugin installed after upgrading Hudson from version 1.374 to 1.375, even if there are no configured Ivy builds on the system.</p>

<p>extract from log:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>07 Sep 2010 6:33:06 PM hudson.model.Hudson$4 onAttained
INFO: Started initialization
07 Sep 2010 6:33:14 PM hudson.model.Hudson$4 onAttained
INFO: Listed all plugins
07 Sep 2010 6:33:14 PM hudson.model.Hudson$4 onAttained
INFO: Prepared all plugins
07 Sep 2010 6:33:15 PM hudson.model.Hudson$4 onTaskFailed
SEVERE: Failed Initializing plugin copyartifact
java.lang.NoClassDefFoundError: hudson/ivy/IvyModuleSetBuild
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:188)
        at hudson.ExtensionList.scoutLoad(ExtensionList.java:245)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:212)
        at hudson.ExtensionList.iterator(ExtensionList.java:113)
        at hudson.ExtensionList.scoutLoad(ExtensionList.java:244)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:212)
        at hudson.ExtensionList.iterator(ExtensionList.java:113)
        at hudson.model.Hudson.getDescriptorByType(Hudson.java:946)
        at hudson.plugins.copyartifact.BuildSelectorParameter.initAliases(BuildSelectorParameter.java:100)
        at hudson.plugins.copyartifact.CopyArtifactPlugin.postInitialize(CopyArtifactPlugin.java:35)
        at hudson.PluginManager$2$1$2.run(PluginManager.java:284)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at hudson.model.Hudson$3.runTask(Hudson.java:679)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: hudson.ivy.IvyModuleSetBuild
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 21 more
</pre>
</div></div>
</pre>
</details>

</ul>
</details>

<p>It actually happens even if you have no Ivy builds configured.<br/>
For some reason the Copy Artifact Plugin v1.8, for example, suddenly also requires the Ivy plugin installed after upgrading Hudson from version 1.374 to 1.375, even if there are no configured Ivy builds on the system.</p>

<p>extract from log:</p>


```
07 Sep 2010 6:33:06 PM hudson.model.Hudson$4 onAttained
INFO: Started initialization
07 Sep 2010 6:33:14 PM hudson.model.Hudson$4 onAttained
INFO: Listed all plugins
07 Sep 2010 6:33:14 PM hudson.model.Hudson$4 onAttained
INFO: Prepared all plugins
07 Sep 2010 6:33:15 PM hudson.model.Hudson$4 onTaskFailed
SEVERE: Failed Initializing plugin copyartifact
java.lang.NoClassDefFoundError: hudson/ivy/IvyModuleSetBuild
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:188)
at hudson.ExtensionList.scoutLoad(ExtensionList.java:245)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:212)
at hudson.ExtensionList.iterator(ExtensionList.java:113)
at hudson.ExtensionList.scoutLoad(ExtensionList.java:244)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:212)
at hudson.ExtensionList.iterator(ExtensionList.java:113)
at hudson.model.Hudson.getDescriptorByType(Hudson.java:946)
at hudson.plugins.copyartifact.BuildSelectorParameter.initAliases(BuildSelectorParameter.java:100)
at hudson.plugins.copyartifact.CopyArtifactPlugin.postInitialize(CopyArtifactPlugin.java:35)
at hudson.PluginManager$2$1$2.run(PluginManager.java:284)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
at hudson.model.Hudson$3.runTask(Hudson.java:679)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: hudson.ivy.IvyModuleSetBuild
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 21 more

```

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/abayer.png" title="abayer's avatar" /> abayer:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141529&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141529">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I don't think that's the Copy Artifact plugin depending on Ivy - I'm pretty sure that's just a case of the Copy Artifact plugin's initialization process uncovering another problem. Somewhere in your Hudson config, there's a reference to the Ivy project type, and it's getting unearthed by Copy Artifact.</p>
</pre>
</details>

</ul>
</details>

<p>I don't think that's the Copy Artifact plugin depending on Ivy - I'm pretty sure that's just a case of the Copy Artifact plugin's initialization process uncovering another problem. Somewhere in your Hudson config, there's a reference to the Ivy project type, and it's getting unearthed by Copy Artifact.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/mindless.png" title="mindless's avatar" /> mindless:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141530&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141530">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>yes, this is just some initialization code in copyartifact that is getting all the Descriptors of its own BuildSelector type.. nothing to do with ivy here, but this must trigger some initialization in Hudson for descriptors of other types, resulting in a stack trace that includes copyartifact.</p>
</pre>
</details>

</ul>
</details>

<p>yes, this is just some initialization code in copyartifact that is getting all the Descriptors of its own BuildSelector type.. nothing to do with ivy here, but this must trigger some initialization in Hudson for descriptors of other types, resulting in a stack trace that includes copyartifact.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/abayer.png" title="abayer's avatar" /> abayer:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-7380?focusedId=141540&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-141540">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Did you ever have the Ivy plugin installed?</p>
</pre>
</details>

</ul>
</details>

<p>Did you ever have the Ivy plugin installed?</p>
