### ISSUE TITLE
[JENKINS-34648] Cannot create new items after upgrade to 2.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#17092]
<p>I just upgraded from version 1.558 to 2.1 and after restart I have some NoSuchMethodError errors.</p>

<pre>
java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:97)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:42)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at hudson.ExtensionList.sort(ExtensionList.java:369)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:289)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.iterator(ExtensionList.java:156)
	at hudson.ExtensionList.get(ExtensionList.java:147)
	at com.cloudbees.jenkins.GitHubPushTrigger$DescriptorImpl.get(GitHubPushTrigger.java:329)
	at org.jenkinsci.plugins.github.migration.Migrator.migrate(Migrator.java:40)
	at org.jenkinsci.plugins.github.GitHubPlugin.postInitialize(GitHubPlugin.java:39)
	at hudson.PluginManager$2$1$2.run(PluginManager.java:433)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$8.runTask(Jenkins.java:1011)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>

<p>When clicking on "New Item", the resulting page is blank and the same error appear in the logs. The rest of the application seems to be operational.</p>

<pre>
WARNING: Error <span class="code-keyword">while</span> serving https:<span class="code-comment">//ci.obiba.org/view/All/itemCategories
</span>...
Caused by: java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.model.View.doItemCategories(View.java:1058)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
</pre>
<p>I do not know if it's relevant but I can see other errors in the logs: </p>

<pre>
Caused by: java.lang.NullPointerException
at hudson.plugins.analysis.core.HealthReportBuilder.computeHealth(HealthReportBuilder.java:47)
at hudson.plugins.analysis.core.AbstractResultAction.getBuildHealth(AbstractResultAction.java:87)
at hudson.model.Job.getBuildHealthReports(Job.java:1122)
</pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ymarcon.png" title="ymarcon's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ymarcon">ymarcon</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648" target="_blank">Cannot create new items after upgrade to 2.1</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>component(s)</b>: core
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2016-05-07T12:37:09+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I just upgraded from version 1.558 to 2.1 and after restart I have some NoSuchMethodError errors.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:97)
	at hudson.ExtensionComponent.compareTo(ExtensionComponent.java:42)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at hudson.ExtensionList.sort(ExtensionList.java:369)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:289)
	at hudson.ExtensionList.getComponents(ExtensionList.java:167)
	at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
	at hudson.ExtensionList.iterator(ExtensionList.java:156)
	at hudson.ExtensionList.get(ExtensionList.java:147)
	at com.cloudbees.jenkins.GitHubPushTrigger$DescriptorImpl.get(GitHubPushTrigger.java:329)
	at org.jenkinsci.plugins.github.migration.Migrator.migrate(Migrator.java:40)
	at org.jenkinsci.plugins.github.GitHubPlugin.postInitialize(GitHubPlugin.java:39)
	at hudson.PluginManager$2$1$2.run(PluginManager.java:433)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$8.runTask(Jenkins.java:1011)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>When clicking on "New Item", the resulting page is blank and the same error appear in the logs. The rest of the application seems to be operational.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">WARNING: Error <span class="code-keyword">while</span> serving https:<span class="code-comment">//ci.obiba.org/view/All/itemCategories
</span>...
Caused by: java.lang.NoSuchMethodError: hudson.model.Messages.ExternalJob_DisplayName()Ljava/lang/<span class="code-object">String</span>;
	at hudson.model.ExternalJob$DescriptorImpl.getDisplayName(ExternalJob.java:132)
	at hudson.model.View.doItemCategories(View.java:1058)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
</pre>
</div></div>
<p>I do not know if it's relevant but I can see other errors in the logs: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: java.lang.NullPointerException
        at hudson.plugins.analysis.core.HealthReportBuilder.computeHealth(HealthReportBuilder.java:47)
        at hudson.plugins.analysis.core.AbstractResultAction.getBuildHealth(AbstractResultAction.java:87)
        at hudson.model.Job.getBuildHealthReports(Job.java:1122)
</pre>
</div></div></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Install from debian package</code></li></ul>
<details><summary><i>2 attachments</i></summary>

- [Screenshot 2016-07-22 12.35.13.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33410/Screenshot%202016-07-22%2012.35.13.png)
  > ![Screenshot 2016-07-22 12.35.13.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33410/Screenshot%202016-07-22%2012.35.13.png)
- [Screenshot 2016-07-22 12.41.31.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33411/Screenshot%202016-07-22%2012.41.31.png)
  > ![Screenshot 2016-07-22 12.41.31.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33411/Screenshot%202016-07-22%2012.41.31.png)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=256705&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-256705">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ymarcon" class="user-hover" rel="ymarcon">ymarcon</a> How are you using this plugin? There are no releases.</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ymarcon" class="user-hover" rel="ymarcon">ymarcon</a> How are you using this plugin? There are no releases.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=256708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-256708">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I've updated the component field. This feature is provided by core.</p>
</pre>
</details>

</ul>
</details>

<p>I've updated the component field. This feature is provided by core.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=256711&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-256711">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Which version of the Monitor External Jobs plugin is this?</p>
</pre>
</details>

</ul>
</details>

<p>Which version of the Monitor External Jobs plugin is this?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=256712&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-256712">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Caused by <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> and resolved by upgrading the External Monitor Job Plugin to 1.4.</p>
</pre>
</details>

</ul>
</details>

<p>Caused by <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> and resolved by upgrading the External Monitor Job Plugin to 1.4.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264857&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264857">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">danielbeck</a> I need to investigate but based on this comment from <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> on <a href="http://stackoverflow.com/a/38519615" class="external-link" target="_blank" rel="nofollow noopener">http://stackoverflow.com/a/38519615</a> it seems that the problem comes back with External Monitor Job Plugin 1.5 <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">danielbeck</a> I need to investigate but based on this comment from <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> on <a href="http://stackoverflow.com/a/38519615" class="external-link" target="_blank" rel="nofollow noopener">http://stackoverflow.com/a/38519615</a> it seems that the problem comes back with External Monitor Job Plugin 1.5 <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264859&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264859">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>But 1.5 is supposed to add the categorisation for Jenkins 2. I'm lost .. I need to test/investigate</p>
</pre>
</details>

</ul>
</details>

<p>But 1.5 is supposed to add the categorisation for Jenkins 2. I'm lost .. I need to test/investigate</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264869&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264869">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> In a fresh installation works fine (Jenkin <tt>2.7.1</tt> LTS + External Monitor Job Plugin <tt>1.5</tt>).</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> In a fresh installation works fine (Jenkin <tt>2.7.1</tt> LTS + External Monitor Job Plugin <tt>1.5</tt>).</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/fdrouet.jpg" title="fdrouet's avatar" /> fdrouet:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264871&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264871">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Mine was just upgraded from an 1.642.4 version</p>
</pre>
</details>

</ul>
</details>

<p>Mine was just upgraded from an 1.642.4 version</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264872&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264872">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> I agree. I did the test too. With a fresh install it is ok. Seems to be a problem with the upgrade or a combination with another plugin. </p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> I agree. I did the test too. With a fresh install it is ok. Seems to be a problem with the upgrade or a combination with another plugin. </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264873&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264873">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> A restart is required after upgrading the plugin. A new issue should be filed with the right component to track this investigation.</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> A restart is required after upgrading the plugin. A new issue should be filed with the right component to track this investigation.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264874&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264874">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I test an upgrade from 1.642.4 to 2.7.1 and it is ok. The plugin is always in version 1.4
 <span class="image-wrap" style=""><a id="33410_thumb" href="https://issues.jenkins.io/secure/attachment/33410/33410_Screenshot+2016-07-22+12.35.13.png" title="Screenshot 2016-07-22 12.35.13.png" file-preview-type="image" file-preview-id="33410" file-preview-title="Screenshot 2016-07-22 12.35.13.png"><img src="https://issues.jenkins.io/secure/thumbnail/33410/_thumb_33410.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p>I try to upgrade all plugins and it is also ok
 <span class="image-wrap" style=""><a id="33411_thumb" href="https://issues.jenkins.io/secure/attachment/33411/33411_Screenshot+2016-07-22+12.41.31.png" title="Screenshot 2016-07-22 12.41.31.png" file-preview-type="image" file-preview-id="33411" file-preview-title="Screenshot 2016-07-22 12.41.31.png"><img src="https://issues.jenkins.io/secure/thumbnail/33411/_thumb_33411.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p>I will analyse more deeply with <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> and will open a dedicated issue with more details</p>
</pre>
</details>

</ul>
</details>

<p>I test an upgrade from 1.642.4 to 2.7.1 and it is ok. The plugin is always in version 1.4<br/>
 <span class="image-wrap" style=""><a id="33410_thumb" href="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33410/Screenshot%202016-07-22%2012.35.13.png" title="Screenshot 2016-07-22 12.35.13.png" file-preview-type="image" file-preview-id="33410" file-preview-title="Screenshot 2016-07-22 12.35.13.png"><img src="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33410/Screenshot%202016-07-22%2012.35.13.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p>I try to upgrade all plugins and it is also ok<br/>
 <span class="image-wrap" style=""><a id="33411_thumb" href="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33411/Screenshot%202016-07-22%2012.41.31.png" title="Screenshot 2016-07-22 12.41.31.png" file-preview-type="image" file-preview-id="33411" file-preview-title="Screenshot 2016-07-22 12.41.31.png"><img src="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/33411/Screenshot%202016-07-22%2012.41.31.png" style="border: 0px solid black" role="presentation"/></a></span> </p>

<p>I will analyse more deeply with <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> and will open a dedicated issue with more details</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264875&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264875">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a>, note that in the first screenshot the icon is not shown because the item categorization was provided as of <tt>1.5</tt>.</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a>, note that in the first screenshot the icon is not shown because the item categorization was provided as of <tt>1.5</tt>.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264880&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264880">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> yes exactly. It is what 1.5 release brings.
I tried to start an instance from a <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> bundle to reproduce the environment with the same set of plugins and I don't reproduce it too.
We will continue to debug on his instance to see what could be specific in his environment to produce this problem</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> yes exactly. It is what 1.5 release brings.<br/>
I tried to start an instance from a <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fdrouet" class="user-hover" rel="fdrouet">fdrouet</a> bundle to reproduce the environment with the same set of plugins and I don't reproduce it too.<br/>
We will continue to debug on his instance to see what could be specific in his environment to produce this problem</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264883&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264883">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> maybe pinned?</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=aheritier" class="user-hover" rel="aheritier">aheritier</a> maybe pinned?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264886&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264886">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Only 1.3 and earlier didn't have <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> </p>
</pre>
</details>

</ul>
</details>

<p>Only 1.3 and earlier didn't have <a href="https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/external-monitor-job-plugin/commit/4175bb5f4fefe0fd7ffa73e195bd65233f83bdf5</a> </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/aheritier.png" title="aheritier's avatar" /> aheritier:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264890&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264890">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">danielbeck</a><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> I identified the bug. It is different and affecting only the latest version of the plugin : <a href="https://issues.jenkins.io/browse/JENKINS-36875" title="Empty screen when creating new jobs" class="issue-link" data-issue-key="JENKINS-36875"><del>JENKINS-36875</del></a></p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">danielbeck</a><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena" class="user-hover" rel="recena">recena</a> I identified the bug. It is different and affecting only the latest version of the plugin : <a href="https://issues.jenkins.io/browse/JENKINS-36875" title="Empty screen when creating new jobs" class="issue-link" data-issue-key="JENKINS-36875"><del>JENKINS-36875</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34648?focusedId=264902&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264902">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>A <a href="https://github.com/jenkinsci/external-monitor-job-plugin/pull/14" class="external-link" target="_blank" rel="nofollow noopener">fix</a> was pushed.</p>
</pre>
</details>

</ul>
</details>

<p>A <a href="https://github.com/jenkinsci/external-monitor-job-plugin/pull/14" class="external-link" target="_blank" rel="nofollow noopener">fix</a> was pushed.</p>
