### ISSUE TITLE
[JENKINS-68882] HudsonFailedToLoad after upgrade to 2.357 with jruby NoClassDefFoundError

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#18133]
<p>After upgrading from 2.347 to 2.357, Jenkins fails to load with following error message.  I was able to manually downgrade back to 2.347 with only a minor issues with a new<img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/help_16.png" height="16" width="16" align="absmiddle" alt="" border="0"/> plugin that I assume got installed during the upgrade.  ("Instance Identity (3.1)Jenkins (2.348) or higher required")</p>

<p> </p>

<pre>
java.lang.NoClassDefFoundError: org/jruby/javasupport/proxy/InternalJavaProxy
	at org.jenkinsci.jruby.JRubyMapper.serializedClass(JRubyMapper.java:20)
	at hudson.util.xstream.MapperDelegate.serializedClass(MapperDelegate.java:41)
	at com.thoughtworks.xstream.mapper.MapperWrapper.serializedClass(MapperWrapper.java:121)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1266)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1228)
	at hudson.XmlFile.write(XmlFile.java:213)
	at jenkins.model.Jenkins.save(Jenkins.java:3545)
	at jenkins.model.Jenkins.<init>(Jenkins.java:1005)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:247)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:261) </pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/gamentek.png" title="gamentek's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gamentek">gamentek</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-68882" target="_blank">HudsonFailedToLoad after upgrade to 2.357 with jruby NoClassDefFoundError</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2022-06-30T07:47:58+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from 2.347 to 2.357, Jenkins fails to load with following error message.  I was able to manually downgrade back to 2.347 with only a minor issues with a new<img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/help_16.png" height="16" width="16" align="absmiddle" alt="" border="0"/> plugin that I assume got installed during the upgrade.  ("Instance Identity (3.1)Jenkins (2.348) or higher required")</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoClassDefFoundError: org/jruby/javasupport/proxy/InternalJavaProxy
	at org.jenkinsci.jruby.JRubyMapper.serializedClass(JRubyMapper.java:20)
	at hudson.util.xstream.MapperDelegate.serializedClass(MapperDelegate.java:41)
	at com.thoughtworks.xstream.mapper.MapperWrapper.serializedClass(MapperWrapper.java:121)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1266)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1228)
	at hudson.XmlFile.write(XmlFile.java:213)
	at jenkins.model.Jenkins.save(Jenkins.java:3545)
	at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:1005)
	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)
	at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:247)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:261) </pre>
</div></div></pre>
</details>
</details>
