### PR TITLE
[JENKINS-21249] Updated Groovy to 2.4.5

### PR DESCRIPTION
**Pull request by daspilker**
Fixes https://issues.jenkins-ci.org/browse/JENKINS-21249.

### CODE REVIEW

**Comment by jglick** [comment]
Of course we would want to go to 2.3 (or whatever the latest version is) if we are going to update at all.

Would need to also run `workflow-plugin` tests against this.

Note that new language features are only likely to work out of the box for the script console and CLI commands, which run a stock embedded Groovy interpreter. Most uses of Groovy by plugins should now be going through the `script-security` plugin, which in a secured system normally uses [groovy-sandbox](https://github.com/kohsuke/groovy-sandbox) and so this would need to be updated to match. And then uses of Groovy from `workflow-plugin` go through [groovy-cps](https://github.com/cloudbees/groovy-cps) (combined with `groovy-sandbox` in some cases), which would also need to support those language features.

**Comment by daspilker** [comment]
I rebased the PR to master, updated Groovy to 2.3.9 and fixed all test failures. Groovy 2.3 introduces  subtle changes in groovysh. And groovy-all.jar contains two classes with major version 51 from groovy-nio. These classes can only be used with NIO classes and that should be detected by animal-sniffer, so I think it's safe to exclude these classes from the byte code version check.

**Comment by daspilker** [comment]
I tried to update the PR to Groovy 2.4.1, but a constructor of the JavaStubGenerator has been [changed](https://github.com/groovy/groovy-core/commit/a90b8b3b70bd4801dec317257d922fcde090ac70#diff-26010797c816400ee2700ba1864a3a6fR62), so I think an additional gmaven runtime for 2.4 is needed. Or an update to GMavenPlus or whatever.

How do we want to continue? I can work on this since it bugs me that I can't use newer Groovy features for the Job DSL plugin.

**Comment by daspilker** [comment]
OK, scratch my last comment. I got it working, I just had to change the POMs so that the 2.0 runtime is used consistently.

I had to add an ugly code block to `hudson.cli.GroovyshCommand` to convert the args into a single command line. Currently the CLI module has no commons-lang or guava dependency, so I could not use a lib for joining the array. I can change that if it's OK to add a dependency.

But still, how do we want to continue? What needs to be done to get this merged?

**Comment by daspilker** [comment]
I updated the pull request to Groovy 2.4.2 and rebased to master.

Is there anything I can do to get this merged?

**Comment by daspilker** [comment]
Updated to Groovy 2.4.3 and rebased to master.

**Comment by jglick** [comment]
Looks like I need to set aside some time to test everything I work on in relation to this, since I expect some regressions: `script-security`, `groovy-sandbox`, `groovy-cps`, `workflow-plugin`, (proprietary) `cloudbees-template`.

**Comment by szpak** [comment]
@jglick Any luck with testing things with Groovy 2.4?

**Comment by jglick** [comment]
Have not tried yet. Thank you for the reminder.

**Comment by marcingrzejszczak** [comment]
+1 for the tests :)

**Comment by kohsuke** [comment]
This topic is selected as one of the sessions of Copenhagen Code Camp. I've pushed `groovy-2.4.4` branch in the repo as a candidate of the merge.

**Comment by kohsuke** [comment]
The coverage of this effort can be [seen here](https://trello.com/c/A9i1Trla/16-groovy-2-4-integration-in-core).

The current status:
* workflow plugin has a number of test failures that appear to be related to [another change I've been working on](https://github.com/jenkinsci/workflow-plugin/pull/131). I think fixing workflow-plugin #131 will address this failure
* @abayer found a test regression in Job DSL plugin, which appears to be caused by a behaviour change that affects test code only.

**Comment by daspilker** [comment]
Thanks to everyone for looking into this. I updated the PR to match https://github.com/jenkinsci/jenkins/tree/groovy-2.4.4.

There has been some more progress:
* https://github.com/jenkinsci/workflow-plugin/pull/131 has been merged in the meantime
* I fixed the Job DSL test regression (https://github.com/jenkinsci/job-dsl-plugin/commit/78ae0c67c3d0b3ce630cca0987c5fba869c8dfb1). So all tests are green when running with a core built from this PR and after fixing all compilation errors introduced by https://github.com/jenkinsci/jenkins/commit/c0260056e5098a21bfacc939ed187bef21abbd93. I will update the core version in Job DSL soon.

**Comment by ArturGajowy** [comment]
@kohsuke @abayer any progress on compatibility with Groovy 2.4.4? We can't wait to using it :)

**Comment by oleg-nenashev** [comment]
Anyway it's a good topic for Jenkins 2.0

**Comment by daspilker** [comment]
Has been merged in 2.0.
