### ISSUE TITLE
[JENKINS-19345] NoClassDefFoundError on project build

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#14872]
<p>I have several free style projects, some of then run on a scheduled basis and some of them using a post commit hook from Github.<br/>
After upgrading to version 1.528 and updating the installed plugins, the automatic some manual builds and all automatic builds started failing, apart from that, another exception it's raised when trying to open the changelog for a build. Here are the exceptions:</p>

<p>1) On the builds that fail here is the exception log:<br/>
tarted by user Federico Saravia<br/>
Building in workspace /var/lib/jenkins/jobs/test-api/workspace<br/>
Checkout:workspace / /var/lib/jenkins/jobs/test-api/workspace - hudson.remoting.LocalChannel@​6281d31b<br/>
Using strategy: Default<br/>
Last Built Revision: Revision e87ed66aeab0ed5b9da96c574c3c326e4a70e332 (origin/development)<br/>
Fetching changes from 1 remote Git repository<br/>
Fetching upstream changes from origin<br/>
Commencing build of Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)<br/>
Checking out Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)<br/>
FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)<br/>
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)<br/>
	... 12 more</p>

<p>On the changelog screen the raised Exception is different (only if there has been changes in the build), the exception is attached.</p>

<p>Another thing, maybe related to the issue is that jenkins tells me that I have old or unreadable data: <br/>
hudson.model.FreeStyleProject	api	NoClassDefFoundError: hudson/tasks/Mailer$UserProperty</p>

<p>I can delete that data, but every time one of the builds fail it comes back.<br/>
I may point that I never installed or used the Mailer plugin. The only plugins I installed and use are the Git plugin and the SSH plugin, so I don't know where this Mailer$UserProperty came from.</p>

<p>I already tried downgrading the plugins to their bundled version but that didn's solve the problem</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/fedesaravia.jpg" title="fedesaravia's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fedesaravia">fedesaravia</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345" target="_blank">NoClassDefFoundError on project build</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ndeloof.png" title="ndeloof's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof">ndeloof</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: core, git-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-10-16T12:25:21+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 9
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I have several free style projects, some of then run on a scheduled basis and some of them using a post commit hook from Github.
After upgrading to version 1.528 and updating the installed plugins, the automatic some manual builds and all automatic builds started failing, apart from that, another exception it's raised when trying to open the changelog for a build. Here are the exceptions:</p>

<p>1) On the builds that fail here is the exception log:
tarted by user Federico Saravia
Building in workspace /var/lib/jenkins/jobs/test-api/workspace
Checkout:workspace / /var/lib/jenkins/jobs/test-api/workspace - hudson.remoting.LocalChannel@6281d31b
Using strategy: Default
Last Built Revision: Revision e87ed66aeab0ed5b9da96c574c3c326e4a70e332 (origin/development)
Fetching changes from 1 remote Git repository
Fetching upstream changes from origin
Commencing build of Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)
Checking out Revision 81206b9ccedc3eeaa1890dc4e960359ad989202d (origin/development)
FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)
	at hudson.model.Run.execute(Run.java:1603)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:247)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 12 more</p>

<p>On the changelog screen the raised Exception is different (only if there has been changes in the build), the exception is attached.</p>

<p>Another thing, maybe related to the issue is that jenkins tells me that I have old or unreadable data: 
hudson.model.FreeStyleProject	api	NoClassDefFoundError: hudson/tasks/Mailer$UserProperty</p>

<p>I can delete that data, but every time one of the builds fail it comes back.
I may point that I never installed or used the Mailer plugin. The only plugins I installed and use are the Git plugin and the SSH plugin, so I don't know where this Mailer$UserProperty came from.</p>

<p>I already tried downgrading the plugins to their bundled version but that didn's solve the problem</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>OS: Debian 7<br/></code></li></ul>
<details><summary><i>1 attachment</i></summary>

- [Exception on changes screen.txt](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-core-cli/refs/heads/main/attachments/24243/Exception%20on%20changes%20screen.txt)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>beardyjay:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=184584&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-184584">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Have ran into the same issue however I am running Jenkins 1.529. Same situation, some manual builds will work however all polled builds fail every time. I do not have the mailer plugin installed and its not within the plugin directory on disk. </p>

<p>OS: Redhat 6.4 
Jenkins: 1.529
Git Plugin: 1.5.0
Git Client Plugin: 1.1.2</p>

<p>Please let me know if you need more information. </p>


<p>Fetching upstream changes from origin
Commencing build of Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)
Checking out Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)
FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:49)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)
	at hudson.model.Run.execute(Run.java:1603)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:247)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
	... 12 more</p>


<p>FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:896)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:420)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:417)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:733)
	at hudson.model.Run.execute(Run.java:1628)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:247)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)</p>

</pre>
</details>

</ul>
</details>

<p>Have ran into the same issue however I am running Jenkins 1.529. Same situation, some manual builds will work however all polled builds fail every time. I do not have the mailer plugin installed and its not within the plugin directory on disk. </p>

<p>OS: Redhat 6.4 <br/>
Jenkins: 1.529<br/>
Git Plugin: 1.5.0<br/>
Git Client Plugin: 1.1.2</p>

<p>Please let me know if you need more information. </p>


<p>Fetching upstream changes from origin<br/>
Commencing build of Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)<br/>
Checking out Revision bac119abc399796146043fa057efe3e485a65256 (origin/dev)<br/>
FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:49)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.access$600(AbstractBuild.java:105)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:681)<br/>
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:581)<br/>
	at hudson.model.Run.execute(Run.java:1603)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)<br/>
	... 12 more</p>


<p>FATAL: hudson/tasks/Mailer$UserProperty<br/>
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty<br/>
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:70)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:59)<br/>
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:23)<br/>
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:922)<br/>
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:896)<br/>
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:420)<br/>
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:417)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:733)<br/>
	at hudson.model.Run.execute(Run.java:1628)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:247)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty<br/>
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)<br/>
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)<br/>
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/fedesaravia.jpg" title="fedesaravia's avatar" /> fedesaravia:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=184722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-184722">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I seem to have found the cause of the problem.
In my case, I use the Git plugin to receive post commit hooks, those commits have the email of the user that made the changes.
The problem is that the plugin parses the changelog and uses a tries to instantiate the class Mailer$UserProperty which is part of the Mailer plugin.
Previous versions of Jenkins had the Mailer plugin bundled into Jenkins core, now that Mailer is a separate plugin, and Git plugin doesn't specify it as a dependency, it fails.
A quick solution is to install or activate the Mailer plugin, I did that and now all the builds are running perfectly</p>
</pre>
</details>

</ul>
</details>

<p>I seem to have found the cause of the problem.<br/>
In my case, I use the Git plugin to receive post commit hooks, those commits have the email of the user that made the changes.<br/>
The problem is that the plugin parses the changelog and uses a tries to instantiate the class Mailer$UserProperty which is part of the Mailer plugin.<br/>
Previous versions of Jenkins had the Mailer plugin bundled into Jenkins core, now that Mailer is a separate plugin, and Git plugin doesn't specify it as a dependency, it fails.<br/>
A quick solution is to install or activate the Mailer plugin, I did that and now all the builds are running perfectly</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>beardyjay:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=184782&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-184782">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Federico, </p>

<p>Thanks for that, I have enabled the mailer plugin and that has fixed the issue for me. </p>
</pre>
</details>

</ul>
</details>

<p>Federico, </p>

<p>Thanks for that, I have enabled the mailer plugin and that has fixed the issue for me. </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=187472&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-187472">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Nicolas De Loof
Path:
 src/main/java/hudson/plugins/git/GitChangeSet.java
<a href="http://jenkins-ci.org/commit/git-plugin/fe92b34775a927fe420d72d5cf8618ed429ee6dd" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-plugin/fe92b34775a927fe420d72d5cf8618ed429ee6dd</a>
Log:
  <span class="error">&#91;FIXED JENKINS-19345&#93;</span> isolate Mailer-dependent code</p>



</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Nicolas De Loof<br/>
Path:<br/>
 src/main/java/hudson/plugins/git/GitChangeSet.java<br/>
<a href="http://jenkins-ci.org/commit/git-plugin/fe92b34775a927fe420d72d5cf8618ed429ee6dd" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-plugin/fe92b34775a927fe420d72d5cf8618ed429ee6dd</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED JENKINS-19345&#93;</span> isolate Mailer-dependent code</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>kwin:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=195460&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195460">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We are running exactly into that issue with the git-plugin 2.0.3. But it works with 2.0.1. So there must be a regression bug in 2.0.3. The weird thing is, that we indeed have the mailer plugin installed and still run into that error with git-plugin 2.0.3</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:80)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:74)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:51)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:29)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:903)
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:877)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:413)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:410)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:710)
	at hudson.model.Run.execute(Run.java:1690)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:246)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 13 more
</pre>
</div></div>
</pre>
</details>

</ul>
</details>

<p>We are running exactly into that issue with the git-plugin 2.0.3. But it works with 2.0.1. So there must be a regression bug in 2.0.3. The weird thing is, that we indeed have the mailer plugin installed and still run into that error with git-plugin 2.0.3</p>

<pre>
FATAL: hudson/tasks/Mailer$UserProperty
java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty
	at hudson.plugins.git.GitChangeLogParser.parseCommit(GitChangeLogParser.java:80)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:74)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:51)
	at hudson.plugins.git.GitChangeLogParser.parse(GitChangeLogParser.java:29)
	at hudson.model.AbstractBuild.calcChangeSet(AbstractBuild.java:903)
	at hudson.model.AbstractBuild.getChangeSet(AbstractBuild.java:877)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:413)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:410)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:710)
	at hudson.model.Run.execute(Run.java:1690)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:246)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.Mailer$UserProperty
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1365)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1068)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:358)
	... 13 more
</pre>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/grahamrhay.jpg" title="grahamrhay's avatar" /> grahamrhay:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=198184&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198184">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm seeing the same problem having just upgraded to Jenkins 1.557. I have version 2.1.0 of the Git plugin, and version 1.8 of the Mailer plugin. Is there a workaround, or versions of the plugins that are known to work together?</p>
</pre>
</details>

</ul>
</details>

<p>I'm seeing the same problem having just upgraded to Jenkins 1.557. I have version 2.1.0 of the Git plugin, and version 1.8 of the Mailer plugin. Is there a workaround, or versions of the plugins that are known to work together?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/grahamrhay.jpg" title="grahamrhay's avatar" /> grahamrhay:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=198210&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198210">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I uninstalled and re-installed the Git plugin (suggested elsewhere), which seems to have "fixed" it.</p>
</pre>
</details>

</ul>
</details>

<p>I uninstalled and re-installed the Git plugin (suggested elsewhere), which seems to have "fixed" it.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/tanis.jpg" title="tanis's avatar" /> tanis:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=198304&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198304">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>@Graham Hay I tried what you suggested but I still get the same error every time the GIT plugin updates from the origin repo.</p>

</pre>
</details>

</ul>
</details>

<p>@​Graham Hay I tried what you suggested but I still get the same error every time the GIT plugin updates from the origin repo.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/grahamrhay.jpg" title="grahamrhay's avatar" /> grahamrhay:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=198305&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198305">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yeah, I still had problems after that too. I've since updated to Jenkins 1.558, and v2.2.0 of the Git plugin; and not seen that error recently. I had a look in the commit log for the plugin, but couldn't see anything that was an obvious fix.</p>
</pre>
</details>

</ul>
</details>

<p>Yeah, I still had problems after that too. I've since updated to Jenkins 1.558, and v2.2.0 of the Git plugin; and not seen that error recently. I had a look in the commit log for the plugin, but couldn't see anything that was an obvious fix.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>panuquets:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-19345?focusedId=213863&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-213863">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I solve this problem downgrading the git-client and git plugins to 1.9.0 and 1.5.0 respectively, as <b>Berg Systeme</b> suggested in his blog:
<a href="http://blog.berg-systeme.de/2014/05/15/downgrade-jenkins-git-plugin/" class="external-link" target="_blank" rel="nofollow noopener">http://blog.berg-systeme.de/2014/05/15/downgrade-jenkins-git-plugin/</a></p>
</pre>
</details>

</ul>
</details>

<p>I solve this problem downgrading the git-client and git plugins to 1.9.0 and 1.5.0 respectively, as <b>Berg Systeme</b> suggested in his blog:<br/>
<a href="http://blog.berg-systeme.de/2014/05/15/downgrade-jenkins-git-plugin/" class="external-link" target="_blank" rel="nofollow noopener">http://blog.berg-systeme.de/2014/05/15/downgrade-jenkins-git-plugin/</a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `is_duplicated_by` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-22051%22">JENKINS-22051</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `is_duplicated_by` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-22115%22">JENKINS-22115</a>]</i>
