### PR TITLE
[JENKINS-43653] - Ensure AbstractItem#delete() NPE safety when checking executors

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This is a regression introduced by https://github.com/jenkinsci/jenkins/pull/2789 in 2.55. See See [JENKINS-43653](https://issues.jenkins-ci.org/browse/JENKINS-43653).

This change adds missing NPE checks and also improves handling of Executables#getParentOf(), which may throw undocumented Runtime exceptions if Executable uses core API below 1.377 and does not implement getParent(). Executor#stop() has been also modified to explicitly handle the issue though there is still the same issue with estimated execution times.

No autotests since the fix is expedited to 2.56.

### Changelog entries

Proposed changelog entries:

* JENKINS-43653: Ensure `NullPointerException` safety when aborting builds during item deletion (regression in 2.55).
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees @stephenc

### CODE REVIEW

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 1]
```diff
@@ -620,9 +621,10 @@ public void delete() throws IOException, InterruptedException {
                 Map<Executor, Queue.Executable> buildsInProgress = new LinkedHashMap<>();
                 for (Computer c : Jenkins.getInstance().getComputers()) {
                     for (Executor e : c.getAllExecutors()) {
-                        WorkUnit workUnit = e.getCurrentWorkUnit();
-                        if (workUnit != null) {
-                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
```
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/AbstractItem.java]: The reported issue is `getParentOf`

**Comment by stephenc** [comment]
Bit overly finicky of an impl

**Review by stephenc — APPROVED** [review]

File: core/src/main/java/hudson/model/Executor.java [hunk 2]
```diff
@@ -843,7 +845,13 @@ public HttpResponse doStop() {
         lock.writeLock().lock(); // need write lock as interrupt will change the field
         try {
             if (executable != null) {
-                Tasks.getOwnerTaskOf(getParentOf(executable)).checkAbortPermission();
+                final SubTask parentOf;
+                try {
+                   parentOf = getParentOfOrFail(executable);
+                } catch(InvocationTargetException ex) {
+                    return HttpResponses.error(500, ex);
```
Comment (jglick) [inline core/src/main/java/hudson/model/Executor.java]: Suffices to just throw this exception (or a wrapper) out of the method.

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 3]
```diff
@@ -59,6 +71,49 @@
...
+     * @param e Executable.
+     * @return Parent subtask from which the executable has been created.
+     *         {@code null} if the Executable is {@code null} OR has incompatible API (old plugin depending on a core older than 1.377)
+     * @since TODO
+     * @see #getParentOfOrFail(hudson.model.Queue.Executable) 
+     */
+    @CheckForNull
+    public static SubTask getParentOfOrNull(@CheckForNull Executable e) {
+        if (e == null) {
+            return null;
```
Comment (jglick) [inline core/src/main/java/hudson/model/queue/Executables.java]: Please do not introduce API methods accepting null arguments for no particular reason. Should be `@Nonnull`.

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 4]
```diff
@@ -59,6 +71,49 @@
...
+     * @param e Executable
+     * @return Parent subtask from which the executable has been created
+     * @throws InvocationTargetException Operation failure due to the usage of incompatible API for old plugin depending on a core older than 1.377
+     * @since TODO
+     */
+    @Nonnull
+    public static SubTask getParentOfOrFail(@Nonnull Executable e) throws InvocationTargetException {
+       try {
+            return getParentOf(e);
+        } catch(RuntimeException | Error ex) {
```
Comment (jglick) [inline core/src/main/java/hudson/model/queue/Executables.java]: `AbstractMethodError` you mean?

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 5]
```diff
@@ -59,6 +71,49 @@
...
+            LOGGER.log(Level.WARNING, formatUnsupportedExecutableAPIMessage(e), ex);
+            return null;
+        }
+    }
+    
+    /**
+     * Get parent subtask from which the executable has been created.
+     * @param e Executable
+     * @return Parent subtask from which the executable has been created
+     * @throws InvocationTargetException Operation failure due to the usage of incompatible API for old plugin depending on a core older than 1.377
```
Comment (jglick) [inline core/src/main/java/hudson/model/queue/Executables.java]: I do not think we need a new method here. Suffices to document the exception in the original, and have `doStop` let it be thrown up as it did before—right?

**Review by jglick — COMMENTED** [review]
I am not fully comfortable with the new API methods in `Executables`; at least they should be `@Restricted(NoExternalUse.class)` for purposes of a hotfix. The `Executor` change also looks gratuitous. The actual issue in `AbstractItem.delete` could have been addressed much more conservatively with a single `try`-`catch`.

**Comment by oleg-nenashev** [comment]
> I am not fully comfortable with the new API methods in Executables; at least they should be @Restricted(NoExternalUse.class) for purposes of a hotfix.

The original issue is in Weekly, backporting of the fixes is not required. I would rather prefer to have a "proper" public API, because plugins are supposed to use this `Executables` utility class to retrieve the tasks instead of directly calling `getParent()` to be compatible with plugins targeting all cores. Do they do it? [Sometimes](https://github.com/search?q=org%3Ajenkinsci+%22queue.Executables%22&type=Code).

Anyway, I doubt it would be sane to introduce such interface changes again

File: core/src/main/java/hudson/model/queue/Executables.java (hunk 4 above)
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/queue/Executables.java]: Nope. It calls the `getParentOf()`method above, which throws these types :(

File: core/src/main/java/hudson/model/Executor.java (hunk 2 above)
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/Executor.java]: This is a non-Restricted public API (it should be restricted, of course), hence I would prefer to keep the current implementation if you do not feel strongly. The user-visible behavior does not change

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 6]
```diff
@@ -88,6 +89,7 @@
 
 import static hudson.model.queue.Executables.getParentOfOrNull;
 import hudson.model.queue.SubTask;
+import java.util.Optional;
```
Comment (stephenc) [inline core/src/main/java/hudson/model/AbstractItem.java]: Unused afaiks

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 7]
```diff
@@ -86,7 +87,9 @@
 import javax.xml.transform.stream.StreamResult;
 import javax.xml.transform.stream.StreamSource;
 
-import static hudson.model.queue.Executables.getParentOf;
+import static hudson.model.queue.Executables.getParentOfOrNull;
+import hudson.model.queue.SubTask;
+import java.util.Optional;
```
Comment (stephenc) [inline core/src/main/java/hudson/model/AbstractItem.java]: Unused import from what I can see

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 8]
```diff
@@ -620,9 +623,11 @@ public void delete() throws IOException, InterruptedException {
                 Map<Executor, Queue.Executable> buildsInProgress = new LinkedHashMap<>();
                 for (Computer c : Jenkins.getInstance().getComputers()) {
                     for (Executor e : c.getAllExecutors()) {
-                        WorkUnit workUnit = e.getCurrentWorkUnit();
-                        if (workUnit != null) {
-                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
+                        final WorkUnit workUnit = e.getCurrentWorkUnit();
+                        final Executable executable = workUnit != null ? workUnit.getExecutable() : null;
+                        final SubTask subtask = executable != null ? getParentOfOrNull(executable) : null;
```
Comment (stephenc) [inline core/src/main/java/hudson/model/AbstractItem.java]: I'm really not liking the OrNull pattern.

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 9]
```diff
@@ -27,19 +27,35 @@
...
+    
     /**
      * Due to the return type change in {@link Executable}, the caller needs a special precaution now.
+     * @param e Executable
+     * @return Discovered subtask
+     * @throws Error Executable type does not offer the {@link Executable#getParent()} method or it fails with {@link Error}
+     * @throws RuntimeException {@link Executable#getParent()} method fails with {@link Error}
      */
-    public static @Nonnull SubTask getParentOf(Executable e) {
+    public static @Nonnull SubTask getParentOf(@Nonnull Executable e)
```
Comment (stephenc) [inline core/src/main/java/hudson/model/queue/Executables.java]: I think the correct thing is to just return `e` in case of those issues and remove all the junk. I'd need to confirm on other than my phone though

File: core/src/main/java/hudson/model/queue/Executables.java (hunk 5 above)
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/queue/Executables.java]: Restricted it for now

**Review by stephenc — CHANGES_REQUESTED** [review]
I think this needs rework on more considered review

**Comment by stephenc** [comment]
I think this is complete over-kill IMHO

Explain why we need any more than

```
diff --git a/core/src/main/java/hudson/model/AbstractItem.java b/core/src/main/java/hudson/model/AbstractItem.java
index 974a940d54..0f44f79f34 100644
--- a/core/src/main/java/hudson/model/AbstractItem.java
+++ b/core/src/main/java/hudson/model/AbstractItem.java
@@ -622,7 +622,8 @@ public abstract class AbstractItem extends Actionable implements Item, HttpDelet
                     for (Executor e : c.getAllExecutors()) {
                         WorkUnit workUnit = e.getCurrentWorkUnit();
                         if (workUnit != null) {
-                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
+                            Queue.Executable exe = workUnit.getExecutable();
+                            Item item = exe != null ? Tasks.getItemOf(getParentOf(exe)) : null;
                             if (item != null) {
                                 while (item != null) {
                                     if (item == this) {
```

?

File: core/src/main/java/hudson/model/AbstractItem.java (hunk 7 above)
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/AbstractItem.java]: Yep, my bad

File: core/src/main/java/hudson/model/AbstractItem.java (hunk 8 above)
Comment (oleg-nenashev) [inline core/src/main/java/hudson/model/AbstractItem.java]: OK, will just kill that method and use try/catch

**Comment by oleg-nenashev** [comment]
> Explain why we need any more than

* workUnit.getExecutable() may return null, will cause NPE in getParentOf
* getParentOf() may throw exceptions in a edge case (plugin implementing old Executable API)

**Comment by stephenc** [comment]
The bug here is that I forgot the race condition where there is a delay between assigning the work unit and assigning the executable. That bug is all we should be fixing here.

GetParentOf will *never* throw exceptions. If you analyse the pre-1.377 signature and the post 1.377 signature you will see that *no* implementation will ever actually throw an exception. javac cannot know what the old signature was and hence does not see that there will never be an exception, hence it requires that we throw something.

Now with Java 9 and modules, we could end up with exceptions... except old code cannot be using modules so will be in the unnamed module so we will be able to setAccessible anyway and in any case we would need to be using modules for the plugin classloader to even have to worry about this.

Just go for the minimalist fix here, the extra API stuff is wholesale unnecessary IMHO (but I will. E pleasantly surprised if you can show my analysis incorrect)

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 10]
```diff
@@ -59,6 +71,29 @@
             }
         }
     }
+    
+    /**
+     * Get parent subtask from which the executable has been created.
+     * @param e Executable
+     * @return Parent subtask from which the executable has been created
+     * @throws InvocationTargetException Operation failure due to the usage of incompatible API for old plugin depending on a core older than 1.377
+     * @since TODO
```
Comment (jglick) [inline core/src/main/java/hudson/model/queue/Executables.java]: If restricting, delete `@since`.

File: core/src/main/java/hudson/model/Executor.java (hunk 2 above)
Comment (jglick) [inline core/src/main/java/hudson/model/Executor.java]: `Executor.doStop` is actually used from plugins AFAIK, so should not be restricted. Better to leave its original implementation alone unless this is somehow required to fix the reported bug.

**Review by jglick — COMMENTED** [review]
From looking at the JIRA issue, all that is required is a simple null check, as in @stephenc’s proposed patch. From mobile I lack the tools to understand the apparently unrelated hypothetical problems you are trying to address in this PR.

**Comment by oleg-nenashev** [comment]
No time to continue arguing this weekend. Will remove everything excepting the NPE fix & follow-up on other things afterwards

**Comment by oleg-nenashev** [comment]
@stephenc E.g. there may be a problem with old version of DistFork plugin: https://issues.jenkins-ci.org/browse/JENKINS-8100 . Unrealistic example, of course. Will investigate on the next week, removing the code right now

**Comment by oleg-nenashev** [comment]
I have left the TODO and Javadoc comment for Executables + Annotations. But there is no code changes left for that exception, only the NPE fix

**Review by stephenc — APPROVED** [review]
Recommend squashing before merge. I don't like adding rumours of JENKINS-8100 without confirmation

**Comment by stephenc** [comment]
JENKINS-8106 fixed JENKINS-8100 please drop the TODO noise

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 11]
```diff
@@ -29,17 +29,32 @@
...
+    
+    // TODO: Investigate if there are still plugins, which do not implement new API (last occurrence: JENKINS-8100)
+    // If yes, improve API by bits, which were proposed in https://github.com/jenkinsci/jenkins/pull/2854
+    
     /**
-     * Due to the return type change in {@link Executable}, the caller needs a special precaution now.
+     * Due to the return type change in {@link Executable} in 1.377, the caller needs a special precaution now.
+     * @param e Executable
+     * @return Discovered subtask
+     * @throws Error Executable type does not offer the {@link Executable#getParent()} method or it fails with {@link Error}.
```
Comment (stephenc) [inline core/src/main/java/hudson/model/queue/Executables.java]: Noise see JENKINS-8106

**Review by stephenc — CHANGES_REQUESTED** [review]

**Comment by stephenc** [comment]
https://github.com/jenkinsci/jenkins/commit/14d17c551a9c8229b59ee1cf702a7e30731764fb

**Comment by stephenc** [comment]
Or https://github.com/jenkinsci/jenkins/commit/dced4d4cd49c02105b789d6ff5367b38497c246c may be the commit and it is https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-7546 (which was fixed in 1.380 rather than 1.388)

**Comment by stephenc** [comment]
In either case the `getParentOf` method was to ensure correct signature handling and those TODOs are just noise.

I am fine with the two `@CheckForNull` annotations though

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 12]
```diff
@@ -620,9 +623,12 @@ public void delete() throws IOException, InterruptedException {
...
                 for (Computer c : Jenkins.getInstance().getComputers()) {
                     for (Executor e : c.getAllExecutors()) {
-                        WorkUnit workUnit = e.getCurrentWorkUnit();
-                        if (workUnit != null) {
-                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
+                        final WorkUnit workUnit = e.getCurrentWorkUnit();
+                        final Executable executable = workUnit != null ? workUnit.getExecutable() : null;
+                        final SubTask subtask = executable != null ? getParentOf(executable) : null;
+                                
+                        if (subtask != null) {
```
Comment (jglick) [inline core/src/main/java/hudson/model/AbstractItem.java]: Could be simplified to only check `executable != null`.

**Review by jglick — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@stephenc OK, dropped it.  The PR will be squashed of course

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 13]
```diff
@@ -77,6 +81,7 @@ public static long getEstimatedDurationFor(@CheckForNull Executable e) {
         try {
             return e.getEstimatedDuration();
         } catch (AbstractMethodError error) {
+            // TODO: according to the code above, e.getparent() may fail. The method also needs to be reworked
```
Comment (stephenc) [inline core/src/main/java/hudson/model/queue/Executables.java]: Noise

File: core/src/main/java/hudson/model/queue/Executables.java [hunk 14]
```diff
@@ -36,10 +36,14 @@
...
+    
     /**
-     * Due to the return type change in {@link Executable}, the caller needs a special precaution now.
+     * Due to the return type change in {@link Executable} in 1.377, the caller needs a special precaution now.
+     * @param e Executable
+     * @return Discovered subtask
      */
-    public static @Nonnull SubTask getParentOf(Executable e) {
+    public static @Nonnull SubTask getParentOf(@Nonnull Executable e) 
+            throws Error, RuntimeException {
```
Comment (stephenc) [inline core/src/main/java/hudson/model/queue/Executables.java]: Throws are unnecessary

**Review by stephenc — APPROVED** [review]
Looks fine, only minor niggles

**Comment by oleg-nenashev** [comment]
@reviewbybees done
@jenkinsci/code-reviewers I would appreciate authorization to merge it (regression in the last weekly). IMHO it is important to get it in this weekly

File: core/src/main/java/hudson/model/queue/Executables.java (hunk 14 above)
Comment (mc1arke) [inline core/src/main/java/hudson/model/queue/Executables.java]: No need to declare a method throwing a RuntimeException

**Review by mc1arke — APPROVED** [review]

File: core/src/main/java/hudson/model/AbstractItem.java [hunk 15]
```diff
@@ -87,6 +88,8 @@
 import javax.xml.transform.stream.StreamSource;
 
 import static hudson.model.queue.Executables.getParentOf;
+import hudson.model.queue.SubTask;
+import java.lang.reflect.InvocationTargetException;
```
Comment (daniel-beck) [inline core/src/main/java/hudson/model/AbstractItem.java]: Unused import?

**Review by daniel-beck — APPROVED** [review]
LTGM assuming squash.

**Comment by oleg-nenashev** [comment]
PR builder passed. Merging it, will cleanup the leftover after the weekly

File: core/src/main/java/hudson/model/queue/Executables.java (hunk 14 above)
Comment (jglick) [inline core/src/main/java/hudson/model/queue/Executables.java]: Agreed with other reviewers, these `throws` should be reverted.
