### ISSUE TITLE
[JENKINS-30969] Job configuration impossible after update to 1.633

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/jenkins#21482]
<p>After updating to 1.633 we are no longer able to configure an existing job. The jenkins log provide the following error message:</p>

<p>WARNUNG: Error while serving <a href="http://jenkins.xxx:8080/job/JOBNAME/descriptorByName/org.jenkinsci.plugins.gitlab.GitlabBuildTrigger/checkCron" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins.xxx:8080/job/JOBNAME/descriptorByName/org.jenkinsci.plugins.gitlab.GitlabBuildTrigger/checkCron</a><br/>
java.lang.reflect.InvocationTargetException<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.lang.reflect.Method.invoke(Method.java:606)<br/>
at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)<br/>
at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)<br/>
at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)<br/>
at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)<br/>
at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br/>
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)<br/>
at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)<br/>
at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br/>
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)<br/>
at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)<br/>
at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br/>
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)<br/>
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)<br/>
at org.kohsuke.stapler.Stapler.service(Stapler.java:238)<br/>
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/>
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)<br/>
at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)<br/>
at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)<br/>
at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)<br/>
at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br/>
at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)<br/>
at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br/>
at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)<br/>
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)<br/>
at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br/>
at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br/>
at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br/>
at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)<br/>
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)<br/>
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)<br/>
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)<br/>
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)<br/>
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)<br/>
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)<br/>
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)<br/>
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)<br/>
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)<br/>
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)<br/>
at org.eclipse.jetty.server.Server.handle(Server.java:370)<br/>
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)<br/>
at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)<br/>
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)<br/>
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)<br/>
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)<br/>
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)<br/>
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)<br/>
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)<br/>
at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:745)<br/>
Caused by: java.lang.NoSuchMethodError: hudson.triggers.TimerTrigger$DescriptorImpl.doCheckSpec(Ljava/lang/String;)Lhudson/util/FormValidation;<br/>
at org.jenkinsci.plugins.gitlab.GitlabBuildTrigger$GitlabBuildTriggerDescriptor.doCheckCron(GitlabBuildTrigger.java:175)<br/>
... 79 more</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=tzuehlsdorff">tzuehlsdorff</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-30969" target="_blank">Job configuration impossible after update to 1.633</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>component(s)</b>: core
<li><b>label(s)</b>: configuration
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-10-15T21:51:52+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-11-24
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After updating to 1.633 we are no longer able to configure an existing job. The jenkins log provide the following error message:</p>

<p>WARNUNG: Error while serving <a href="http://jenkins.xxx:8080/job/JOBNAME/descriptorByName/org.jenkinsci.plugins.gitlab.GitlabBuildTrigger/checkCron" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins.xxx:8080/job/JOBNAME/descriptorByName/org.jenkinsci.plugins.gitlab.GitlabBuildTrigger/checkCron</a>
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: hudson.triggers.TimerTrigger$DescriptorImpl.doCheckSpec(Ljava/lang/String;)Lhudson/util/FormValidation;
        at org.jenkinsci.plugins.gitlab.GitlabBuildTrigger$GitlabBuildTriggerDescriptor.doCheckCron(GitlabBuildTrigger.java:175)
        ... 79 more</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Ubuntu 14.04.3 LTS<br/>
Jenkins 1.633 (provided by <a href="http://pkg.jenkins-ci.org/debian/)">http://pkg.jenkins-ci.org/debian/)</a>
```
</details>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a href="https://github.com/jenkinsci/jenkins/issues?q=is%3Aissue%20%22jira_issue_key%3DJENKINS-30820%22">JENKINS-30820</a>]</i>
